import test from 'node:test';
import assert from 'node:assert/strict';
import fs from 'node:fs';
import {searchTopics} from '../app/search-core.mjs';
const read=p=>JSON.parse(fs.readFileSync(new URL(p,import.meta.url),'utf8'));
const catalog=read('../app/dossier.json'),full=read('../public/repository.json');
test('all 300 compendium pages appear once and every table is preserved',()=>{const pages=full.topics.flatMap(t=>t.pages||[]);assert.equal(pages.length,300);assert.deepEqual([...new Set(pages.map(p=>p.page))].sort((a,b)=>a-b),Array.from({length:300},(_,i)=>i+1));assert.equal(pages.reduce((n,p)=>n+p.tables.length,0),281)});
test('all legacy technical links resolve publicly and detail files match',()=>{const ids=new Set(full.topics.map(t=>t.id));assert.equal(ids.size,150);for(const id of read('../private/legacy-ids.json'))assert.ok(ids.has(id),id);for(const t of full.topics){assert.deepEqual(read('../public/library/'+t.id+'.json'),t);for(const id of t.related||[])assert.ok(ids.has(id),id)}});
test('chapter citations have public references',()=>{const ids=new Set(full.sources.map(s=>s.id));assert.equal(ids.size,120);for(const t of full.topics)for(const id of t.sourceIds||[])assert.ok(ids.has(id),id)});
test('full-content search retrieves scientific and engineering terms',()=>{for(const q of ['Reader V1','digital twin','heteroresistance','BME690','PIMS','stem cells','campus audit'])assert.ok(searchTopics(catalog.topics,q).length,q)});
test('published catalogue has no owner paths or credential assignments',()=>{const s=JSON.stringify(full);assert.doesNotMatch(s,/C:[\\/]|ADMIN_EMAILS|api[_-]?key["']?\s*[:=]/i)});
