import test from 'node:test';
import assert from 'node:assert/strict';
import {initialReview,reviewReducer as reducer,effectiveMm,REFERENCES,compareMeasurements,captureReport,reportCsv} from '../app/measurement-model.mjs';
import {demoDiscs,classify,threshold} from '../app/demo-rules.mjs';
const at='2026-09-12T10:00:00.000Z';
const act=(s,a)=>reducer(s,{at,...a});
function run(scenario='clean'){let s=act(initialReview(),{type:'scenario',value:scenario});s=act(s,{type:'run'});return act(s,{type:'complete',generation:s.generation});}
function correct(s,code,mm,reason='Boundary inspected',timestamp=at){s=act(s,{type:'draft',code,patch:{mm:String(mm),reason}});return act(s,{type:'apply',code,at:timestamp});}
test('unknown disc and rule identifiers never produce categories',()=>{for(const [code,profile] of [['wat','A'],['CIP','wat'],['__proto__','A']]){assert.equal(threshold(code,profile),null);assert.equal(classify(25,code,profile),null)}const s=run();assert.equal(act(s,{type:'profile',value:'wat'}),s);assert.equal(act(s,{type:'apply',code:'wat'}),s);});
test('corrections need a reason; cancelling preserves values and approvals',()=>{let s=act(run(),{type:'confirm',code:'CIP'});const before=s.records; s=act(s,{type:'draft',code:'CIP',patch:{mm:'23',reason:'  '}});assert.equal(act(s,{type:'apply',code:'CIP'}),s);assert.equal(act(s,{type:'confirm',code:'AMC'}),s);assert.throws(()=>captureReport(s,at));s=act(s,{type:'cancel',code:'CIP'});assert.deepEqual(s.records,before);assert.equal(s.corrections.length,0);});
test('successive corrections retain originals, reasons, timestamps and invalidate review',()=>{let s=act(run('fuzzy'),{type:'verify',code:'CIP',value:true});s=act(s,{type:'confirm',code:'CIP'});assert.equal(s.records.CIP.review,'confirmed');s=correct(s,'CIP',24);assert.equal(s.records.CIP.review,'pending');assert.equal(s.records.CIP.verified,false);s=correct(s,'CIP',23,'Second inspection','2026-09-12T10:01:00Z');s=correct(s,'CIP',25.4,'Restore original','2026-09-12T10:02:00Z');assert.equal(s.records.CIP.originalMm,25.4);assert.equal(effectiveMm(s.records.CIP),25.4);assert.deepEqual(s.corrections.map(e=>[e.beforeMm,e.afterMm]),[[25.4,24],[24,23],[23,25.4]]);assert.match(s.corrections[2].reviewer,/demo identity/);assert.equal(s.corrections[1].timestamp,'2026-09-12T10:01:00Z');assert.equal(act(s,{type:'confirm',code:'CIP'}),s);});
test('invalid corrections do not apply and drafts on other discs also block confirmation',()=>{for(const value of ['', 'NaN','Infinity','5','41']){let s=run();s=act(s,{type:'draft',code:'AMC',patch:{mm:value,reason:'test'}});assert.equal(act(s,{type:'apply',code:'AMC'}),s);assert.equal(act(s,{type:'confirm',code:'CIP'}),s)}});
test('changing fictional profile keeps provenance, recalculates categories and clears approvals',()=>{let s=correct(run(),'AMC',23);s=act(s,{type:'confirm',code:'CIP'});const corrections=s.corrections;const originals=Object.values(s.records).map(r=>r.originalMm);s=act(s,{type:'profile',value:'B'});assert.equal(s.corrections,corrections);assert.deepEqual(Object.values(s.records).map(r=>r.originalMm),originals);assert.ok(Object.values(s.records).every(r=>r.review==='pending'&&!r.verified));assert.equal(classify(effectiveMm(s.records.CIP),'CIP','B'),'I');assert.equal(effectiveMm(s.records.AMC),23);});
test('scenario changes cancel processing; stale completion cannot finish the next run',()=>{let s=act(initialReview(),{type:'run'});const old=s.generation;s=act(s,{type:'scenario',value:'unreadable'});assert.equal(s.status,'idle');assert.equal(act(s,{type:'complete',generation:old}),s);s=act(s,{type:'run'});assert.equal(act(s,{type:'complete',generation:old}),s);s=act(s,{type:'complete',generation:s.generation});assert.equal(s.scenario,'unreadable');assert.equal(s.status,'complete');s=act(s,{type:'scenario',value:'clean'});assert.equal(s.status,'idle');assert.equal(s.records.CIP.originalMm,null);});
test('unreadable run abstains, cannot approve or edit and exports an incomplete report',()=>{const s=run('unreadable');for(const d of demoDiscs){assert.equal(effectiveMm(s.records[d.code]),null);assert.equal(classify(effectiveMm(s.records[d.code]),d.code,s.profile),null);for(const type of ['draft','apply','verify','confirm'])assert.equal(act(s,{type,code:d.code,value:true,patch:{mm:'24',reason:'test'}}),s)}const r=captureReport(s,at);assert.match(r.outcome,/Incomplete.*recapture/i);assert.ok(r.results.every(d=>d.mm===null&&d.originalMm===null&&d.interpretation===null&&d.review!=='confirmed'));assert.equal(r.comparison.pairedCount,0);assert.equal(r.comparison.meanDifference,null);assert.equal(r.comparison.categoryAgreement,null);});
test('fixed independent comparison values and exact aggregate calculations',()=>{const s=run(),a=compareMeasurements(s.records,'A'),b=compareMeasurements(s.records,'B');assert.deepEqual(REFERENCES,{CIP:24,AMC:23,MEM:28,GEN:18,SXT:26,AMP:14});assert.ok(Object.isFrozen(REFERENCES));assert.deepEqual(a.rows.map(r=>r.difference),[1.4,-4,0,.6,0,-8]);assert.equal(a.pairedCount,6);assert.ok(Math.abs(a.meanDifference+10/6)<1e-10);assert.ok(Math.abs(a.meanAbsoluteDifference-14/6)<1e-10);assert.equal(a.categoryAgreement,4/6*100);assert.equal(b.categoryAgreement,100);const invalid=structuredClone(s.records);invalid.CIP.correctedMm=NaN;assert.equal(compareMeasurements(invalid,'A').pairedCount,5);assert.equal(compareMeasurements(s.records,'unknown').pairedCount,0);correct(s,'AMP',40);assert.equal(REFERENCES.AMP,14);assert.equal(demoDiscs.find(d=>d.code==='AMP').mm,6);});
test('immutable snapshot and JSON/CSV preserve the same effective values and provenance',()=>{let s=correct(run(),'CIP',24,'Reason with comma, and "quote"');const r=captureReport(s,at),json=JSON.stringify(r),csv=reportCsv(r);s=correct(s,'CIP',22,'Subsequent correction');s=act(s,{type:'profile',value:'B'});assert.equal(JSON.stringify(r),json);assert.equal(reportCsv(r),csv);assert.ok(Object.isFrozen(r)&&Object.isFrozen(r.results[0])&&Object.isFrozen(r.correctionEvents));assert.equal(r.results[0].mm,24);assert.equal(r.results[0].originalMm,25.4);assert.equal(r.results[0].correctedMm,24);assert.equal(r.ruleVersion,'fictional-A-v1');assert.match(csv,/"25.4","24","24","24","0","S"/);assert.match(csv,/referenceFixtureId/);assert.match(csv,/Reason with comma/);assert.equal(JSON.parse(json).correctionEvents.length,1);});
test('excluded comparison rows normalize invalid numbers and contain no fictional categories',()=>{const s=run('unreadable'),r=captureReport(s,at);assert.ok(r.comparison.rows.every(row=>row.category===null&&row.referenceCategory===null&&row.difference===null));const invalid=run();invalid.records.CIP.correctedMm=NaN;const snap=captureReport(invalid,at);assert.equal(snap.results[0].mm,null);assert.equal(snap.comparison.rows[0].mm,null);assert.equal(snap.comparison.rows[0].category,null);assert.equal(snap.comparison.rows[0].referenceCategory,null);assert.ok(!reportCsv(snap).includes('NaN'));});
