"use client";
import {useEffect,useState} from 'react';
import LibraryView,{type Library} from './library-view';
import {GuidedPitch} from './discovery';
type Item={id:string;url:string;tool:string;claim:string;verdict:string;action:string;status:string;evidence:string;official:string[]};
type Supplement={id:string;title:string;text:string;links:string[]};
type Review={status:string;note:string};
export default function AdminWorkspace(){
 const [data,setData]=useState<{library:Library;intake:Item[];supplements:Supplement[]}|null>(null);
 const [error,setError]=useState(''),[query,setQuery]=useState(''),[pitch,setPitch]=useState(false);
 const [notes,setNotes]=useState<Record<string,Review>>({}),[feedback,setFeedback]=useState<Record<string,string>>({});
 const load=async()=>{setError('');try{const r=await fetch('/api/private/library',{cache:'no-store'});if(!r.ok)throw Error('Access could not be verified. Sign in again to continue.');setData(await r.json());const rr=await fetch('/api/private/reviews',{cache:'no-store'});const b=await rr.json() as {error:string;rows:({id:string}&Review)[]};if(!rr.ok)throw Error(b.error);setNotes(Object.fromEntries(b.rows.map(x=>[x.id,{status:x.status,note:x.note}])))}catch(e){setError(e instanceof Error?e.message:'Library unavailable')}};
 useEffect(()=>{void load()},[]);
 const save=async(id:string,state:Review)=>{setFeedback(s=>({...s,[id]:'Saving…'}));try{const r=await fetch('/api/private/reviews',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({id,...state})});const b=await r.json() as {error?:string};if(!r.ok)throw Error(b.error||'Save failed');setFeedback(s=>({...s,[id]:'Saved'}))}catch(e){setFeedback(s=>({...s,[id]:e instanceof Error?e.message:'Could not save. Your draft is preserved.'}))}};
 const matches=(v:unknown)=>JSON.stringify(v).toLowerCase().includes(query.toLowerCase());
 if(pitch)return <GuidedPitch onExit={()=>setPitch(false)} onNavigate={hash=>{setPitch(false);location.href='/#'+hash}}/>;
 return <>
 <section className="section"><span className="eyebrow">OWNER WORKSPACE</span><h1>Review. Connect. Present.</h1><p>Technical detail and implementation decisions for admin review.</p><label className="explorer-search">Search tools, ideas and opportunities<input type="search" aria-label="Search all implementation ideas" value={query} onChange={e=>setQuery(e.target.value)}/></label><div className="atelier-actions"><button className="solid-link" onClick={()=>setPitch(true)}>Open presentation</button><a href="#implementation">Implementation queue</a><a href="#apex">Technical library</a><a href="#additional">Additional ideas</a><a href="#concepts">Concept references</a></div>{error&&<p role="alert">{error} <button onClick={load}>Reload</button></p>}</section>
 {data?<><LibraryView data={data.library} privateView/>
 <section className="section" id="concepts"><h2>Concept references</h2><p>Design studies and supplied drawings, not verified CAD or validated instruments.</p><div className="topic-grid">{['hardware/apex-concept.webp','hardware/apex-exploded.webp','reference/isometric.jpeg','reference/wireframe.jpeg','reference/orthographic.jpeg'].map((name,i)=><figure key={name}><a href={'/api/private/assets?name='+encodeURIComponent(name)} target="_blank" rel="noreferrer"><img loading="lazy" src={'/api/private/assets?name='+encodeURIComponent(name)} alt={['Instrument concept','Exploded concept','Isometric concept reference','Wireframe concept reference','Orthographic concept reference'][i]} style={{width:'100%',borderRadius:12}}/></a><figcaption>{['Instrument concept','Exploded concept','Isometric reference','Wireframe reference','Orthographic reference'][i]}</figcaption></figure>)}</div></section>
 <section className="section" id="additional"><h2>Additional ideas and opportunities</h2><div className="intake-list">{data.supplements.filter(matches).map(t=><article key={t.id} id={t.id}><small>{t.id}</small><h3>{t.title}</h3><p>{t.text}</p>{t.links.map((link,i)=><a key={link} href={link} target="_blank" rel="noreferrer">Reference {i+1} ↗</a>)}</article>)}</div></section>
 <section id="implementation" className="section"><h2>Implementation queue</h2><p>{data.intake.filter(matches).length} of {data.intake.length} recommendations. Research and installed integrations are separate states.</p><div className="intake-list">{data.intake.filter(matches).map(t=>{const state=notes[t.id]||{status:'pending',note:''};return <article id={t.id} key={t.id}><small>{t.id} · {t.status}</small><h3>{t.tool}</h3><p>{t.claim}</p><p>{t.action}</p><small>{t.evidence}</small><p><a href={t.url} target="_blank" rel="noreferrer">Original recommendation ↗</a>{t.official.map((u,i)=><a key={u} href={u} target="_blank" rel="noreferrer"> · Reference {i+1} ↗</a>)}</p><label>Review status<select value={state.status} onChange={e=>setNotes(n=>({...n,[t.id]:{...state,status:e.target.value}}))}>{['pending','ready','implemented','needs-input','not-selected'].map(s=><option key={s}>{s}</option>)}</select></label><label>Review note<textarea value={state.note} maxLength={4000} onChange={e=>setNotes(n=>({...n,[t.id]:{...state,note:e.target.value}}))}/></label><button onClick={()=>save(t.id,state)}>Save review</button><p role="status">{feedback[t.id]}</p></article>})}</div></section>
 </>:<p className="section" role="status">{error?'Library not loaded.':'Opening the protected library…'}</p>}</>
}
