"use client";
import {useEffect,useId,useReducer,useState} from "react";
import {ArrowRight,Play,RotateCcw,FileText,SlidersHorizontal,ShieldCheck,Camera,Ruler,Users,Check,ScanLine,Focus,Layers3,TriangleAlert} from "lucide-react";
import {Dialog,DialogContent,DialogHeader,DialogTitle} from "@/components/ui/dialog";
import {demoDiscs,threshold,classify} from "./demo-rules.mjs";
import {SCENARIOS,REFERENCE_ID,REVIEWER,initialReview,reviewReducer,effectiveMm,validMm,readability,compareMeasurements,captureReport,reportCsv,type Measurement,type Comparison,type Report} from "./measurement-model.mjs";
const stages=["Plate registration","Scale reference","Disc identification","Boundary segmentation","Diameter measurement","Illustrative rules","Human review"];
const mmText=(mm:number|null)=>mm===null?"Not available":mm.toFixed(1);
const signed=(n:number|null)=>n===null?"Not available":`${n>0?"+":""}${n.toFixed(2)}`;
export function MetrologyPlate({records,selected="CIP",onSelect,overlay=true,scenario="clean",processing=false,draftMm}:{records:Record<string,Measurement>;selected?:string;onSelect?:(code:string)=>void;overlay?:boolean;scenario?:string;processing?:boolean;draftMm?:number}){
 const id=useId().replace(/:/g,"");const unreadable=scenario==="unreadable";
 return <svg viewBox="0 0 360 360" className="metrology-plate" role="group" aria-label={unreadable?"Unreadable synthetic plate illustration":"Synthetic 90 mm plate with six discs"} data-plate-view={overlay?"overlay":"raw"}>
  <defs><radialGradient id={`${id}-agar`}><stop stopColor="#515942"/><stop offset="1" stopColor="#293a33"/></radialGradient><clipPath id={`${id}-scan`}><circle cx="180" cy="180" r="159"/></clipPath></defs>
  <circle cx="180" cy="180" r="163" fill="#151f1c" stroke="#92aea0" strokeWidth="2"/><circle cx="180" cy="180" r="160" fill={`url(#${id}-agar)`}/>
  {unreadable?<g aria-hidden="true" clipPath={`url(#${id}-scan)`}><path d="M45 120 Q180 20 300 180 T70 270 Q20 190 220 70" fill="none" stroke="#92916d" strokeWidth="64" opacity=".45"/><text x="180" y="180" textAnchor="middle" fill="#fff" fontSize="14">Recapture required</text></g>:demoDiscs.map((d,i)=>{
   const angle=(i*60-90)*Math.PI/180;let x=180+100*Math.cos(angle),y=180+100*Math.sin(angle);if(scenario==="overlap"&&i===1){x-=30;y-=25}
   const measured=effectiveMm(records[d.code]);const radius=d.mm/90*160;const effectiveRadius=measured===null?radius:measured/90*160;
   return <g key={d.code} role={onSelect?"button":undefined} tabIndex={onSelect?0:undefined} aria-label={overlay?`${d.code} effective zone ${mmText(measured)}${measured===null?"":" millimetres"}`:`${d.code} original illustration ${d.mm.toFixed(1)} millimetres`} onClick={()=>onSelect?.(d.code)} onKeyDown={e=>{if(e.key==="Enter"||e.key===" "){e.preventDefault();onSelect?.(d.code)}}} className={onSelect?"disc-target":""}>
    <circle cx={x} cy={y} r={Math.max(radius,22)} fill="transparent"/><circle data-original-zone={d.code} cx={x} cy={y} r={radius} fill="#bfcea321"/>
    <circle cx={x} cy={y} r={6/90*160} fill="#dddacb"/><text x={x} y={y+3} textAnchor="middle" fill="#25342c" fontSize="8" fontWeight="700">{d.code}</text>
    {overlay&&measured!==null&&<><circle cx={x} cy={y} r={effectiveRadius} fill="none" stroke={selected===d.code?"#78ddcc":"#d8dfae88"} strokeWidth={selected===d.code?2:1} strokeDasharray={scenario==="fuzzy"?"2 4":undefined}/><line x1={x-effectiveRadius} x2={x+effectiveRadius} y1={y} y2={y} stroke="#a9dcc9" strokeWidth=".8"/><text x={x} y={y+effectiveRadius+14} textAnchor="middle" fontSize="9" fill="#ebf2e9">{measured.toFixed(1)} mm</text>{selected===d.code&&draftMm!==undefined&&validMm(draftMm)&&draftMm!==measured&&<g data-draft-zone={d.code}><circle cx={x} cy={y} r={draftMm/90*160} fill="none" stroke="#e7a1ff" strokeWidth="2" strokeDasharray="4 3"/><text x={x} y={y-effectiveRadius-12} textAnchor="middle" fill="#f3c9ff" fontSize="10">Draft {draftMm.toFixed(1)} mm</text></g>}</>}
   </g>;
  })}
  {processing&&<g clipPath={`url(#${id}-scan)`} aria-hidden="true"><rect className="plate-scan" x="20" y="30" width="320" height="28" fill="#78ddcc44"/><line className="plate-scan" x1="20" x2="340" y1="30" y2="30" stroke="#9cfff0" strokeWidth="2"/></g>}
  <text x="180" y="350" textAnchor="middle" fill="#a4b6ad" fontSize="9">SYNTHETIC ILLUSTRATION • NOT A PATIENT IMAGE</text>
 </svg>;
}
function ValidationComparison({comparison,profile}:{comparison:Comparison;profile:string}){
 return <div className="validation-comparison"><p>Teaching comparisons, not clinical accuracy. Independent fixed synthetic reference: <code>{REFERENCE_ID}</code>. Difference = effective minus reference.</p>
  <div className="comparison-summary"><div><small>Paired discs</small><b>{comparison.pairedCount||"Not available"}</b></div><div><small>Mean difference</small><b>{signed(comparison.meanDifference)}{comparison.pairedCount?" mm":""}</b></div><div><small>Mean absolute difference</small><b>{comparison.meanAbsoluteDifference===null?"Not available":comparison.meanAbsoluteDifference.toFixed(2)+" mm"}</b></div><div><small>Category agreement</small><b>{comparison.categoryAgreement===null?"Not available":comparison.categoryAgreement.toFixed(1)+"%"}</b></div></div>
 {comparison.pairedCount>0&&<div className="comparison-scroll" tabIndex={0} role="region" aria-label="Validation measurements"><table><caption>Fictional profile {profile} · {comparison.excludedCount} excluded pairs</caption><thead><tr><th>Disc</th><th>Original mm</th><th>Effective mm</th><th>Reference mm</th><th>Difference mm</th><th>Demo / reference category</th><th>Agreement</th></tr></thead><tbody>{comparison.rows.map(r=><tr key={r.code}><th>{r.code}</th><td>{mmText(r.originalMm)}</td><td>{mmText(r.mm)}</td><td>{mmText(r.referenceMm)}</td><td>{signed(r.difference)}</td><td>{r.category??"Not available"} / {r.referenceCategory??"Not available"}</td><td>{r.agreement===null?"Not available":r.agreement?"Agree":"Differ"}</td></tr>)}</tbody></table></div>}
 </div>;
}
export default function AnalysisWorkbench(){
 const [state,dispatch]=useReducer(reviewReducer,undefined,initialReview);const [selected,setSelected]=useState("CIP");const [overlay,setOverlay]=useState(true);const [step,setStep]=useState(0);const [report,setReport]=useState<Report|null>(null);
 const send=(action:Parameters<typeof reviewReducer>[1])=>dispatch({...action,at:new Date().toISOString()});
 const running=state.status==="processing",complete=state.status==="complete",readable=complete&&state.scenario!=="unreadable";
 useEffect(()=>{if(!running)return;setStep(0);const token=state.generation;let n=0;const timer=setInterval(()=>{n++;setStep(n);if(n===7){clearInterval(timer);dispatch({type:"complete",generation:token,at:new Date().toISOString()})}},500);return()=>clearInterval(timer)},[running,state.generation]);
 const current=state.records[selected],effective=effectiveMm(current),draft=state.drafts[selected],pending=Object.keys(state.drafts).length>0;
 const cut=threshold(selected,state.profile);const comparison=compareMeasurements(state.records,state.profile);
 const confirmed=Object.values(state.records).filter(r=>r.review==='confirmed').length;
 const journey=running?1:complete?(confirmed===6?3:2):0;
 const draftValue=draft?.mm.trim()&&validMm(Number(draft.mm))?Number(draft.mm):undefined;
 const canApply=!!draft&&draft.mm.trim()!==""&&validMm(Number(draft.mm))&&!!draft.reason.trim()&&Math.round(Number(draft.mm)*10)/10!==effective;
 const reportRecords=report?Object.fromEntries(report.results.map(r=>[r.code,r])):{};
 const download=(format:"json"|"csv")=>{if(!report)return;const text=format==="json"?JSON.stringify(report,null,2):reportCsv(report);const url=URL.createObjectURL(new Blob([text],{type:format==="json"?"application/json":"text/csv;charset=utf-8"}));const a=document.createElement("a");a.href=url;a.download=`AMReye.AI-${report.runId}-synthetic-report.${format}`;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000)};
 return <div className="workbench"><div className="workbench-banner"><ShieldCheck size={18}/><span>Synthetic workbench · Fictional thresholds · No patient-image processing</span></div>
  <div className="demo-scenarios" aria-label="Choose a visual quality scenario">{([{id:'clean',title:'Clear plate',copy:'Start with visible boundaries.',icon:Focus},{id:'fuzzy',title:'Fuzzy edges',copy:'Decide what needs closer review.',icon:ScanLine},{id:'overlap',title:'Overlapping zones',copy:'See why context matters.',icon:Layers3},{id:'unreadable',title:'Unreadable image',copy:'Know when to stop and recapture.',icon:TriangleAlert}]).map(({id,title,copy,icon:Icon})=><button key={id} aria-pressed={state.scenario===id} onClick={()=>send({type:'scenario',value:id})}><Icon/><b>{title}</b><span>{copy}</span></button>)}</div>
  <ol className="demo-journey" aria-label="Demonstration progress">{[['Choose plate',Camera],['Measure',Ruler],['Human review',Users],['Record',FileText]].map(([label,Icon],i)=>{const StageIcon=Icon as typeof Camera;return <li key={String(label)} data-active={journey===i} data-complete={journey>i}><span>{journey>i?<Check/>:<StageIcon/>}</span><b>{String(label)}</b><small>{i===0?'Synthetic input':i===1?(running?stages[Math.min(step,6)]:complete?'Run complete':'Ready to run'):i===2?`${confirmed} / 6 confirmed`:'Traceable demo report'}</small></li>})}</ol>
  <div className="workbench-controls"><label>Rule profile<select value={state.profile} onChange={e=>send({type:"profile",value:e.target.value})}><option value="A">Fictional profile A</option><option value="B">Fictional profile B</option></select></label><label>QC scenario<select value={state.scenario} onChange={e=>send({type:"scenario",value:e.target.value})}>{Object.entries(SCENARIOS).map(([key,label])=><option key={key} value={key}>{label}</option>)}</select></label><button className="text-link" onClick={()=>send({type:"reset"})}><RotateCcw size={16}/>Reset demo</button><small className="run-note">Each scenario needs a new run. Starting another run clears its measurements and correction history; export a report first to keep a copy.</small></div>
  <div className="workbench-grid"><div className="workbench-visual"><div className="view-switch"><button aria-pressed={!overlay} onClick={()=>setOverlay(false)}>Raw illustration</button><button aria-pressed={overlay} onClick={()=>setOverlay(true)}>Measurement overlay</button></div><MetrologyPlate records={state.records} selected={selected} onSelect={readable?setSelected:undefined} overlay={overlay&&complete} processing={running} scenario={state.scenario} draftMm={draftValue}/><p>{draftValue!==undefined?'Purple dashed boundary = unapplied draft. The original and effective measurement are unchanged.':readable?'Select a disc on the plate, then adjust its boundary below. The original illustration stays unchanged.':'Choose a plate scenario and run the demonstration.'}</p><button className="solid-link" disabled={running} onClick={()=>send({type:"run"})}><Play size={16}/>{running?stages[Math.min(step,6)]:complete?"Run demonstration again":"Run synthetic analysis"}</button><div className="metrology-progress" role="status">{running?stages[Math.min(step,6)]:complete?`Run complete · ${readability(state)}`:"Ready · run analysis to begin"}<progress value={complete?7:running?step:0} max={7}/></div>{readable&&cut&&effective!==null&&<div className="measurement-gauge"><div className="measurement-gauge-label"><b>{selected} · {effective.toFixed(1)} mm</b><span>Fictional profile {state.profile}</span></div><div className="measurement-gauge-track" aria-hidden="true"><span className="gauge-r" style={{width:((cut.r-6)/34*100)+'%'}}>R</span><span className="gauge-i" style={{width:((cut.s-cut.r)/34*100)+'%'}}>I</span><span className="gauge-s" style={{width:((40-cut.s)/34*100)+'%'}}>S</span><i style={{left:((effective-6)/34*100)+'%'}}/>{draftValue!==undefined&&<i className="gauge-draft" style={{left:((draftValue-6)/34*100)+'%'}}/>}</div><div className="measurement-gauge-scale"><span>6 mm</span><span>40 mm</span></div><label className="demo-preview-slider">Preview a boundary change<input type="range" aria-label="Preview boundary diameter" min="6" max="40" step="0.1" value={draftValue??effective} onChange={e=>{setOverlay(true);send({type:"draft",code:selected,patch:{mm:e.target.value}})}}/></label><button onClick={()=>document.querySelector(".caliper-panel")?.scrollIntoView({block:"center"})}>Review and apply the draft<ArrowRight size={16}/></button><small>White: effective measurement. Purple: draft. Categories are fictional, not CLSI/EUCAST interpretation.</small></div>}</div>
   <div className="workbench-results">
    {readable&&<div className="triage-bar">{["S","I","R"].map(k=><span className={`triage-${k}`} key={k}>{k}: {demoDiscs.filter(d=>classify(effectiveMm(state.records[d.code]),d.code,state.profile)===k).length}</span>)}<small>Fictional categories</small></div>}
    {state.scenario!=="clean"&&<div className="qc-banner" role="status">{state.scenario==="unreadable"?"Unreadable / recapture required. No zone measurements or susceptibility interpretations can be produced.":state.scenario==="fuzzy"?"Ambiguous margins. Inspect each simulated boundary before confirmation.":"Overlapping boundaries. Inspect each simulated boundary before confirmation; no synergy inference."}<b>Invented quality scenario.</b></div>}
    <div className="metrology-table"><table><thead><tr><th>Disc</th><th>Effective zone</th><th>Demo category</th></tr></thead><tbody>{demoDiscs.map(d=>{const value=effectiveMm(state.records[d.code]);const category=classify(value,d.code,state.profile);return <tr key={d.code} data-selected={selected===d.code}><td><button disabled={!readable} onClick={()=>setSelected(d.code)}>{d.code}{state.drafts[d.code]&&<span className="pending-disc">Draft</span>}<small>{d.name}</small></button></td><td>{value===null?"Not available":value.toFixed(1)+" mm"}</td><td>{category?<span className={`triage-${category}`}>{category}</span>:"Not available"}</td></tr>})}</tbody></table></div>
    {pending&&<div className="pending-corrections" role="status"><b>Pending corrections</b>{Object.keys(state.drafts).map(code=><button key={code} onClick={()=>setSelected(code)}>Review {code}</button>)}<button onClick={()=>Object.keys(state.drafts).forEach(code=>send({type:"cancel",code}))}>Cancel all drafts</button></div>}
    {readable?<div className="caliper-panel"><h3><SlidersHorizontal size={18}/>{selected} · Measurement review</h3><p>Original <b>{mmText(current.originalMm)} mm</b> · Effective <b>{mmText(effective)} mm</b></p><label>Correction diameter (mm)<input aria-label="Correction diameter in millimetres" type="number" min="6" max="40" step="0.1" value={draft?.mm??effective??""} onChange={e=>send({type:"draft",code:selected,patch:{mm:e.target.value}})}/></label><input aria-label="Adjust correction diameter" type="range" min="6" max="40" step=".1" value={draft?.mm&&validMm(Number(draft.mm))?draft.mm:effective??6} onChange={e=>send({type:"draft",code:selected,patch:{mm:e.target.value}})}/>
     <label>Correction reason <textarea value={draft?.reason??""} placeholder="Explain why this example boundary needs correction" onChange={e=>send({type:"draft",code:selected,patch:{reason:e.target.value}})}/></label>
     <div className="review-actions"><button disabled={!canApply} onClick={()=>send({type:"apply",code:selected})}>Apply correction</button><button disabled={!draft} onClick={()=>send({type:"cancel",code:selected})}>Cancel draft</button></div>
     {pending&&<p role="status">Pending correction. Apply or cancel all drafts before confirming a review or opening a report. Use a value from 6 to 40 mm and a non-empty reason.</p>}
     {cut&&<small>Fictional {state.profile}: S ≥ {cut.s} mm · I {cut.r} to &lt;{cut.s} mm · R &lt; {cut.r} mm. These are not CLSI/EUCAST cutoffs.</small>}
     <label className="verify-boundary"><input type="checkbox" checked={current.verified} onChange={e=>send({type:"verify",code:selected,value:e.target.checked})}/>I inspected this simulated boundary{state.scenario!=="clean"?" (required)":""}</label>
     <p role="status">Review: <b>{current.review}</b> · {REVIEWER}</p><div className="review-actions"><button disabled={pending||(state.scenario!=="clean"&&!current.verified)} onClick={()=>send({type:"confirm",code:selected})}>Confirm review</button><button disabled={pending} onClick={()=>send({type:"reject",code:selected})}>Reject</button></div>
     {state.corrections.some(e=>e.discCode===selected)&&<details className="correction-history"><summary>Correction history for {selected}</summary>{state.corrections.filter(e=>e.discCode===selected).map((e,i)=><p key={i}><b>{e.beforeMm} → {e.afterMm} mm</b> · {e.reason}<br/><time>{e.timestamp}</time> · {e.reviewer}</p>)}</details>}
    </div>:<p className="review-hint">{complete?"Recapture is required. You can open an incomplete report documenting this outcome.":"Run the analysis to enable measurement editing and review."}</p>}
    <button className="text-link" disabled={!complete||pending} onClick={()=>setReport(captureReport(state,new Date().toISOString()))}><FileText size={18}/>Open demonstration report<ArrowRight size={16}/></button>
   </div></div>
  <details className="standards-explanation"><summary>Validation comparison</summary><ValidationComparison comparison={comparison} profile={state.profile}/></details>
  <details className="standards-explanation"><summary>What do these fictional rules demonstrate?</summary><p>Image measurement, human review and rule interpretation are separate steps. Changing the fictional profile preserves measurements and correction history, recalculates categories and clears approvals. No specimen is tested, no clinical accuracy is established, and no authenticated reviewer signs these examples.</p><a href="?topic=research-validation-mode#apex">Validation roadmap ↗</a>{" · "}<a href="?topic=research-readability#apex">Readability and recapture ↗</a>{" · "}<a href="https://www.eucast.org/bacteria/methodology-and-instructions/disk-diffusion-and-quality-control/" target="_blank" rel="noreferrer">EUCAST methodology ↗</a></details>
  <Dialog open={report!==null} onOpenChange={open=>{if(!open)setReport(null)}}><DialogContent className="demo-report" aria-describedby={undefined}><DialogHeader><DialogTitle>AST demonstration record</DialogTitle></DialogHeader>{report&&<><strong className="report-warning">SYNTHETIC · NOT FOR CLINICAL USE</strong><p>{report.timestamp}<br/>{report.runId} · {report.reviewer}<br/>Readability: {report.readability}<br/>{report.outcome}</p><p>AMReye.AI demonstration laboratory · AMR-CORE-01 (simulated). E. coli example, Mueller-Hinton agar and 0.5 McFarland equivalent are illustrative metadata. No specimen was tested.</p><p>Snapshot schema {report.schemaVersion} · {report.ruleVersion} · {report.referenceFixtureId}</p>
   <div className="report-plates"><figure><MetrologyPlate records={reportRecords} overlay={false} scenario={report.scenario}/><figcaption>Unchanged original illustration</figcaption></figure><figure><MetrologyPlate records={reportRecords} scenario={report.scenario}/><figcaption>Effective measurement overlay</figcaption></figure></div>
   <div className="report-table"><table><thead><tr><th>Disc / example µg</th><th>Original / effective mm</th><th>Fictional {report.profile}</th><th>Review / boundary</th></tr></thead><tbody>{report.results.map(r=><tr key={r.code}><td>{r.code} / {r.potency}<small>{r.name}</small></td><td>{mmText(r.originalMm)} / {mmText(r.mm)}</td><td>{r.interpretation??"Not available"}</td><td>{r.review} / {r.verified?"verified":"unverified"}</td></tr>)}</tbody></table></div>
   <ValidationComparison comparison={report.comparison} profile={report.profile}/><div className="report-provenance"><h3>Correction events ({report.correctionEvents.length})</h3>{report.correctionEvents.map((e,i)=><p key={i}>{e.discCode}: {e.beforeMm} → {e.afterMm} mm · {e.reason}<br/>{e.timestamp} · {e.reviewer}</p>)}<h3>Run audit</h3>{report.audit.map((e,i)=><p key={i}>{e.timestamp} · {e.reviewer} · {e.action}</p>)}</div><p>{report.signature} This immutable snapshot is shared by print, JSON and CSV.</p><div className="atelier-actions report-actions"><button className="solid-link" onClick={()=>window.print()}>Print / save PDF</button><button className="text-link" onClick={()=>download("json")}>Export JSON</button><button className="text-link" onClick={()=>download("csv")}>Export CSV</button></div></>}</DialogContent></Dialog>
 </div>;
}
