"use client";
import {useState,useEffect,useMemo} from 'react';
import {Search,ArrowUpRight,ChevronRight,BookOpen,Download,Link as LinkIcon,Trophy,FileText,Boxes,FlaskConical,ShieldCheck} from 'lucide-react';
import {Dialog,DialogContent,DialogHeader,DialogTitle} from '@/components/ui/dialog';
import data from './dossier.json';
const categories=['All','Subsystems','Use cases','Architecture','Validation','Product & costs','Documentation'];
const wins=[
 {date:'03 SEP 2026',title:'APEX XR flagship dossier completed',copy:'A detailed engineering and product proposal covering 22 subsystems, 20 use cases, architecture, validation and evidence boundaries.',href:'#apex',action:'Browse 97 topics'},
 {date:'03 SEP 2026',title:'GSF Round 2 pitch package prepared',copy:'A complete AMR-Eye pitch package was produced around the startup, problem, solution, business model, milestones and support request.',href:'#business',action:'Open business story'},
 {date:'04 SEP 2026',title:'Interactive knowledge explorer launched',copy:'The full dossier became a searchable, filterable and linked repository with topic links and a source register.',href:'#apex',action:'Search the library'},
 {date:'05 SEP 2026',title:'3D hardware concept made interactive',copy:'Six conceptual hardware layers can be rotated, isolated and inspected with touch-aware controls and conservative product labels.',href:'#hardware',action:'Explore hardware'},
 {date:'05 SEP 2026',title:'Synthetic AST review workflow completed',copy:'The seven-stage demonstration supports per-antibiotic selection, human approval, correction records and an exportable demo report.',href:'#demo',action:'Run analysis'},
 {date:'06 SEP 2026',title:'Product ecosystem published',copy:'Product tiers, SaaS–BAHU, edge, cloud, connectivity, support, research and public-health concepts were organized into one interactive workspace.',href:'#products',action:'Explore products'},
];
export default function ApexExplorer(){
 const [limit,setLimit]=useState(6);
 const [query,setQuery]=useState('');const [category,setCategory]=useState('All');const [status,setStatus]=useState('All');const [topic,setTopic]=useState<string|null>(null);const [notice,setNotice]=useState('');
 useEffect(()=>{const read=()=>{setTopic(location.hash==="#apex"?new URLSearchParams(location.search).get('topic'):null);if(location.hash==="#sources"){const el=document.getElementById("sources") as HTMLDetailsElement;if(el)el.open=true}};read();window.addEventListener('popstate',read);window.addEventListener('hashchange',read);return()=>{window.removeEventListener('popstate',read);window.removeEventListener('hashchange',read)}},[]);
 const select=(id:string|null)=>{setTopic(id);setNotice('');const url=new URL(location.href);if(id){url.searchParams.set('topic',id);url.hash='apex';}else url.searchParams.delete('topic');history.pushState({},'',url);window.dispatchEvent(new HashChangeEvent('hashchange'))};
 useEffect(()=>setLimit(6),[query,category,status]);
 const selected=data.topics.find(t=>t.id===topic);
 const matches=useMemo(()=>data.topics.filter(t=>(category==='All'||t.category===category)&&(status==='All'||t.status===status)&&JSON.stringify(t).toLowerCase().includes(query.toLowerCase())),[query,category,status]);
 const sourceText=(s:string)=>s.split(/(\[S\d+(?:-S?\d+)?\])/g).map((part,i)=>/^\[S/.test(part)?<a key={i} href="#sources" onClick={()=>{select(null);const el=document.getElementById("sources") as HTMLDetailsElement;if(el)el.open=true}} className="source-ref">{part}</a>:part);
 return <section className="section apex-section" id="apex">
 <div className="apex-heading"><div><span className="section-kicker">AMR-EYE · PROJECT REPOSITORY</span><h2>Everything AMR-Eye.<br/><em>One living library.</em></h2><p>Explore the flagship dossier, product architecture, subsystems, use cases, validation boundaries, sources and completed project milestones.</p></div><div className="apex-summary"><span className="scope-tag scope-proposed">Living repository</span><p>Begin with a summary, choose a subject, then open the full technical record and its sources.</p><a href="#recognition">Wins & recognition <ChevronRight size={18}/></a></div></div>
 <div className="repository-index" aria-label="Repository contents">
  <button onClick={()=>{setCategory('All');setQuery('');setStatus('All')}}><FileText/><b>{data.topics.length}</b><span>Dossier topics</span><small>Complete APEX XR knowledge base</small></button>
  <button onClick={()=>{setCategory('Subsystems');setQuery('');setStatus('All')}}><Boxes/><b>22</b><span>Subsystems</span><small>Hardware and platform layers</small></button>
  <button onClick={()=>{setCategory('Use cases');setQuery('');setStatus('All')}}><FlaskConical/><b>20</b><span>Use cases</span><small>Laboratory and research contexts</small></button>
  <button onClick={()=>{setCategory('Validation');setQuery('');setStatus('All')}}><ShieldCheck/><b>06</b><span>Validation stages</span><small>Evidence before deployment</small></button>
 </div>
 <section className="wins-panel" id="project-progress"><div className="wins-title"><Trophy/><div><small>DEVELOPMENT RECORD</small><h3>Development milestones</h3></div><p>Completed AMR-Eye deliverables recorded by date. No clinical-performance claim is implied.</p></div><div className="wins-grid">{wins.map((win,index)=><a href={win.href} key={win.title}><span>{String(index+1).padStart(2,'0')}</span><small>{win.date}</small><h4>{win.title}</h4><p>{win.copy}</p><b>{win.action}<ArrowUpRight/></b></a>)}</div></section>
 <div className="apex-shortcuts">{[['Subsystems','22','Hardware subsystems'],['Use cases','20','Detailed use cases'],['Architecture','04','Software layers'],['Validation','→','Evidence & safety']].map(([cat,n,label])=><button key={cat} onClick={()=>{setCategory(cat);setQuery('');setStatus('All')}} aria-pressed={category===cat}><b>{n}</b><span>{label}</span><ArrowUpRight/></button>)}</div>
 <div className="explorer-controls"><label className="explorer-search"><Search size={20}/><input type="search" value={query} onChange={e=>setQuery(e.target.value)} placeholder="Search MIC, sensors, hospital workflows…" aria-label="Search APEX documentation"/></label><label className="status-filter">Maturity<select value={status} onChange={e=>setStatus(e.target.value)}><option>All</option><option>Proposed product</option><option>Future R&D</option></select></label></div>
 <div className="explorer-tabs" aria-label="Documentation categories">{categories.map(c=><button key={c} onClick={()=>setCategory(c)} aria-pressed={category===c}>{c}</button>)}</div>
 <p className="explorer-count" aria-live="polite">{matches.length} topics · Source: APEX XR dossier v1.0 · Specifications and cost estimates are dated proposals.</p>
 <div className="topic-grid">{matches.slice(0,limit).map(t=><button key={t.id} className="topic-card" onClick={()=>select(t.id)}><span>{t.category}<ArrowUpRight size={18}/></span><h3>{t.title}</h3><p>{t.text[0]||t.tables[0]?.[1]?.[1]||'Explore the full design and its validation requirements.'}</p><small className={t.status==='Future R&D'?'future-text':''}>{t.status} <ChevronRight size={15}/></small></button>)}</div>
 {matches.length>limit&&<button className="secondary-action load-topics" onClick={()=>setLimit(n=>n+12)}>Show more topics ({matches.length-limit} remaining)</button>}
 {!matches.length&&<div className="empty-topics"><Search/><h3>No matching topics</h3><p>Try a shorter term or clear the filters.</p><button onClick={()=>{setQuery('');setCategory('All');setStatus('All')}}>Reset search</button></div>}
 <details className="source-register" id="sources"><summary><BookOpen/> Documentation & source register <ChevronRight/></summary><p>Content is adapted from the APEX XR flagship dossier dated 03 September 2026. External specifications, standards and prices must be checked again before procurement or clinical implementation. Internal design sources are identified for provenance.</p><div className="source-grid">{data.sources.map(s=><div key={s.id}><b>{s.id}</b>{s.url?<a href={s.url} target="_blank" rel="noopener noreferrer">{s.title}<ArrowUpRight size={16}/></a>:<span>{s.title}<small>Internal design input</small></span>}</div>)}</div></details>
 <Dialog open={!!selected} onOpenChange={open=>!open&&select(null)}><DialogContent className="apex-dialog"><DialogHeader><span className="section-kicker">{selected?.category} · {selected?.status}</span><DialogTitle>{selected?.title}</DialogTitle></DialogHeader><div className="topic-actions"><button onClick={async()=>{try{await navigator.clipboard.writeText(location.href);setNotice('Topic link copied')}catch{setNotice('Copy the topic URL from your address bar')}}}><LinkIcon size={17}/>Copy link</button><span role="status">{notice}</span></div><div className="topic-content">{selected?.text.map((p,i)=><p key={i}>{sourceText(p)}</p>)}{selected?.tables.map((table,i)=><div className="topic-table-scroll" key={i}><table><thead><tr>{table[0].map((c,k)=><th key={k}>{sourceText(c)}</th>)}</tr></thead><tbody>{table.slice(1).map((r,j)=><tr key={j}>{r.map((c,k)=><td key={k} data-label={table[0][k]}>{sourceText(c)}</td>)}</tr>)}</tbody></table></div>)}<p className="topic-boundary">Dossier v1.0 · 03 September 2026. This is a design and planning record. Current PoC, proposed implementation and research directions do not establish clinical performance or regulatory clearance.</p><a href="#sources" onClick={()=>{select(null);setTimeout(()=>{const el=document.getElementById('sources') as HTMLDetailsElement;if(el)el.open=true},0)}}>View cited sources <ArrowUpRight size={16}/></a></div></DialogContent></Dialog>
 </section>
}
