"use client";
import {useState,useEffect,useMemo} from 'react';
import {Search,ArrowUpRight,ChevronRight,BookOpen,Download,Link as LinkIcon} from 'lucide-react';
import {Dialog,DialogContent,DialogHeader,DialogTitle} from '@/components/ui/dialog';
import data from './dossier.json';
const categories=['All','Subsystems','Use cases','Architecture','Validation','Product & costs','Documentation'];
export default function ApexExplorer(){
 const [limit,setLimit]=useState(9);
 const [query,setQuery]=useState('');const [category,setCategory]=useState('All');const [status,setStatus]=useState('All');const [topic,setTopic]=useState<string|null>(null);const [notice,setNotice]=useState('');
 useEffect(()=>{const read=()=>setTopic(new URLSearchParams(location.search).get('topic'));read();window.addEventListener('popstate',read);return()=>window.removeEventListener('popstate',read)},[]);
 const select=(id:string|null)=>{setTopic(id);setNotice('');const url=new URL(location.href);if(id)url.searchParams.set('topic',id);else url.searchParams.delete('topic');history.pushState({},'',url)};
 useEffect(()=>setLimit(9),[query,category,status]);
 const selected=data.topics.find(t=>t.id===topic);
 const matches=useMemo(()=>data.topics.filter(t=>(category==='All'||t.category===category)&&(status==='All'||t.status===status)&&JSON.stringify(t).toLowerCase().includes(query.toLowerCase())),[query,category,status]);
 const sourceText=(s:string)=>s.split(/(\[S\d+(?:-S?\d+)?\])/g).map((part,i)=>/^\[S/.test(part)?<a key={i} href="#sources" onClick={()=>{select(null);const el=document.getElementById("sources") as HTMLDetailsElement;if(el)el.open=true}} className="source-ref">{part}</a>:part);
 const download=()=>{if(!selected)return;const blob=new Blob([`AMR-Eye APEX XR | Dossier 03 September 2026\n${selected.title}\n${selected.status}\n\n${selected.text.join('\n\n')}\n\n${selected.tables.map(t=>t.map(r=>r.join(' | ')).join('\n')).join('\n\n')}\n\nDesign proposal, not evidence of clinical validation.`],{type:'text/plain;charset=utf-8'});const url=URL.createObjectURL(blob);const a=document.createElement('a');a.href=url;a.download=selected.id+'.txt';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000)};
 return <section className="section apex-section" id="apex">
 <div className="apex-heading"><div><span className="section-kicker">APEX XR · KNOWLEDGE EXPLORER</span><h2>The full platform.<br/><em>Open every layer.</em></h2><p>Explore the 03 September 2026 flagship dossier: the purpose, workflow, outputs and validation boundaries behind each proposed capability.</p></div><div className="apex-summary"><span className="scope-tag scope-proposed">Proposed product</span><p>Current work is at PoC / prototype stage. APEX XR is an engineering proposal. Simulations on this site do not operate laboratory hardware.</p><a href="#demo">Try the synthetic AST workflow <ChevronRight size={18}/></a></div></div>
 <div className="apex-shortcuts">{[['Subsystems','22','Hardware subsystems'],['Use cases','20','Detailed use cases'],['Architecture','04','Software layers'],['Validation','→','Evidence & safety']].map(([cat,n,label])=><button key={cat} onClick={()=>{setCategory(cat);setQuery('');setStatus('All')}} aria-pressed={category===cat}><b>{n}</b><span>{label}</span><ArrowUpRight/></button>)}</div>
 <div className="explorer-controls"><label className="explorer-search"><Search size={20}/><input type="search" value={query} onChange={e=>setQuery(e.target.value)} placeholder="Search MIC, sensors, hospital workflows…" aria-label="Search APEX documentation"/></label><label className="status-filter">Maturity<select value={status} onChange={e=>setStatus(e.target.value)}><option>All</option><option>Proposed product</option><option>Future R&D</option></select></label></div>
 <div className="explorer-tabs" aria-label="Documentation categories">{categories.map(c=><button key={c} onClick={()=>setCategory(c)} aria-pressed={category===c}>{c}</button>)}</div>
 <p className="explorer-count" aria-live="polite">{matches.length} topics · Source: APEX XR dossier v1.0 · Specifications and cost estimates are dated proposals.</p>
 <div className="topic-grid">{matches.slice(0,limit).map(t=><button key={t.id} className="topic-card" onClick={()=>select(t.id)}><span>{t.category}<ArrowUpRight size={18}/></span><h3>{t.title}</h3><p>{t.text[0]||t.tables[0]?.[1]?.[1]||'Explore the full design and its validation requirements.'}</p><small className={t.status==='Future R&D'?'future-text':''}>{t.status} <ChevronRight size={15}/></small></button>)}</div>
 {matches.length>limit&&<button className="secondary-action load-topics" onClick={()=>setLimit(n=>n+12)}>Show more topics ({matches.length-limit} remaining)</button>}
 {!matches.length&&<div className="empty-topics"><Search/><h3>No matching topics</h3><p>Try a shorter term or clear the filters.</p><button onClick={()=>{setQuery('');setCategory('All');setStatus('All')}}>Reset search</button></div>}
 <details className="source-register" id="sources"><summary><BookOpen/> Documentation & source register <ChevronRight/></summary><p>Content is adapted from the APEX XR flagship dossier dated 03 September 2026. External specifications, standards and prices must be checked again before procurement or clinical implementation. Internal design sources are identified for provenance.</p><div className="source-grid">{data.sources.map(s=><div key={s.id}><b>{s.id}</b>{s.url?<a href={s.url} target="_blank" rel="noopener noreferrer">{s.title}<ArrowUpRight size={16}/></a>:<span>{s.title}<small>Internal design input</small></span>}</div>)}</div></details>
 <Dialog open={!!selected} onOpenChange={open=>!open&&select(null)}><DialogContent className="apex-dialog"><DialogHeader><span className="section-kicker">{selected?.category} · {selected?.status}</span><DialogTitle>{selected?.title}</DialogTitle></DialogHeader><div className="topic-actions"><button onClick={download}><Download size={17}/>Save topic</button><button onClick={async()=>{try{await navigator.clipboard.writeText(location.href);setNotice('Topic link copied')}catch{setNotice('Copy the topic URL from your address bar')}}}><LinkIcon size={17}/>Copy link</button><span role="status">{notice}</span></div><div className="topic-content">{selected?.text.map((p,i)=><p key={i}>{sourceText(p)}</p>)}{selected?.tables.map((table,i)=><div className="topic-table-scroll" key={i}><table><thead><tr>{table[0].map((c,k)=><th key={k}>{sourceText(c)}</th>)}</tr></thead><tbody>{table.slice(1).map((r,j)=><tr key={j}>{r.map((c,k)=><td key={k}>{sourceText(c)}</td>)}</tr>)}</tbody></table></div>)}<p className="topic-boundary">Dossier v1.0 · 03 September 2026. This is a design and planning record. Current PoC, proposed implementation and research directions do not establish clinical performance or regulatory clearance.</p><a href="#sources" onClick={()=>{select(null);setTimeout(()=>{const el=document.getElementById('sources') as HTMLDetailsElement;if(el)el.open=true},0)}}>View cited sources <ArrowUpRight size={16}/></a></div></DialogContent></Dialog>
 </section>
}
