"use client";
import {useState} from 'react';
import {Copy, Mail, Check} from 'lucide-react';
const email='namdevshirodkar20@gmail.com';
export default function Contact(){
 const [notice,setNotice]=useState(''),[draft,setDraft]=useState('');
 const copy=async(value:string,label:string)=>{try{await navigator.clipboard.writeText(value);setNotice(label+' copied.')}catch{setNotice('Copy is unavailable. Select the visible text below and copy it.')}};
 return <div className="contact-panel"><div><span className="eyebrow">DEMO · RESEARCH · COLLABORATION</span><h2>Talk to the team.</h2><p>Tell us about your laboratory, research question or interest in the project.</p><a href={'mailto:'+email}>{email}</a><button className="text-link" onClick={()=>copy(email,'Email address')}><Copy size={16}/>Copy email address</button><p>Prepare an email below, then copy it or open your email app. This website does not send or store your message.</p></div><form onChange={()=>{setDraft("");setNotice("")}} onSubmit={e=>{e.preventDefault();const form=new FormData(e.currentTarget);const text=`Hello AMReye.AI team,\n\nName: ${form.get('name')}\nReply email: ${form.get('email')}\nOrganisation: ${form.get('organisation')||'Not specified'}\n\n${form.get('message')}`;setDraft(text);setNotice('Your draft is ready. Copy it or open it in your email app. Nothing has been sent.')}}><ol className="contact-progress" aria-label="Contact steps"><li data-active={!draft}><span>1</span>Write</li><li data-active={!!draft}><span>2</span>Review draft</li><li><span>3</span>You send</li></ol><label>Name<input name="name" autoComplete="name" required minLength={2} maxLength={120}/></label><label>Email<input name="email" type="email" autoComplete="email" required maxLength={254}/></label><label>Organisation <span>(optional)</span><input name="organisation" autoComplete="organization" maxLength={180}/></label><label>Message<textarea name="message" rows={5} required minLength={10} maxLength={4000}/></label><button type="submit" className="solid-link"><Mail size={18}/>Prepare message</button><p role="status" className="contact-notice">{notice}</p>{draft&&<div className="contact-draft"><label>Ready to copy<textarea rows={8} readOnly value={draft}/></label><div className="atelier-actions"><button type="button" className="solid-link" onClick={()=>copy(draft,'Message')}><Check size={17}/>Copy message</button><a href={`mailto:${email}?subject=${encodeURIComponent('AMReye.AI enquiry')}&body=${encodeURIComponent(draft)}`}>Open email app ↗</a></div></div>}</form></div>
}
