"use client";
import {useEffect,useState} from "react";
import {ArrowUpRight,ArrowRight,ArrowLeft,ChevronRight,Search,Menu,Play,X,BookOpen,Layers3,Microscope,Users,Compass} from "lucide-react";
import {Sheet,SheetContent,SheetHeader,SheetTitle,SheetTrigger} from "@/components/ui/sheet";

export const directory = [
 {title:"Discover",copy:"The idea, the people, the path ahead.",links:[["Overview","home"],["The problem","problem"],["Who it is for","pathways"],["Wins & recognition","recognition"],["Our team","team"],["About & contact","about"],["The business","business"],["Roadmap","roadmap"]]},
 {title:"Explore",copy:"Products and hands-on demonstrations.",links:[["Product collection","products"],["Plate analysis demo","demo"],["Hardware & 3D","hardware"],["Lab console","console"],["AMR network","network"],["Project guide","guide"]]},
 {title:"Go deeper",copy:"The complete project knowledge base.",links:[["Library · all 83 topics","apex"],["Technology","technology"],["Imaging","imaging"],["Sensor modules","modules"],["Plate digital twin","twin"],["SaaS–BAHU","bahu"],["Architecture","architecture"],["Connectivity","integration"],["Automation","automation"],["One Health applications","applications"],["Competitive context","positioning"],["Technology glossary","wall"],["Source register","sources"],["Development record","project-progress"]]}
];
export function SiteNavigation({active,onPitch}:{active:string;onPitch:()=>void}){
 const [open,setOpen]=useState(false);
 return <><a href="#main-content" className="skip-link" onClick={e=>{e.preventDefault();document.getElementById("main-content")?.focus()}}>Skip to content</a><header className="atelier-header"><a className="atelier-brand" href="#home"><img src="/amr-eye-icon.png" alt="" width="28" height="28"/>AMR-Eye<span>.AI</span></a><nav aria-label="Primary navigation">{[["Discover","home"],["Products","products"],["Library","apex"],["Team","team"]].map(([label,id])=><a key={id} href={`#${id}`} aria-current={active===id?"page":undefined}>{label}</a>)}</nav><div><button className="brief-button" onClick={onPitch}><Play size={14}/>Quick pitch</button><Sheet open={open} onOpenChange={setOpen}><SheetTrigger className="index-button" aria-label="Open site directory"><Menu size={21}/></SheetTrigger><SheetContent className="atelier-menu" aria-describedby={undefined}><SheetHeader><SheetTitle>Explore AMR-Eye.</SheetTitle></SheetHeader><p className="menu-intro">Start anywhere. Go as deep as you want.</p><div className="menu-columns">{directory.map(group=><div key={group.title}><h3>{group.title}</h3><p>{group.copy}</p><nav aria-label={group.title}>{group.links.map(([label,id])=><a key={id} href={`#${id}`} onClick={()=>setOpen(false)}>{label}<ArrowUpRight size={16}/></a>)}</nav></div>)}</div></SheetContent></Sheet></div></header><nav className="atelier-dock" aria-label="Mobile navigation">{[["Home","home",Compass],["Products","products",Layers3],["Demo","demo",Microscope],["Library","apex",BookOpen]].map(([label,id,Icon])=>{const I=Icon as typeof Compass;return <a key={id as string} href={`#${id}`} aria-current={active===id?"page":undefined}><I size={19}/><span>{label as string}</span></a>})}</nav></>;
}
export function HomeDirectory({onPitch}:{onPitch:()=>void}){
 return <section id="home" className="home-directory"><div className="atelier-hero"><div className="atelier-hero-copy"><span className="eyebrow">MICROBIOLOGY. CONNECTED.</span><h1>Measure the plate.<br/><span>Connect the record.</span></h1><p>AMR-Eye explores calibrated imaging for antibiotic susceptibility testing: plate measurements, qualified human review and a connected laboratory record.</p><div className="atelier-actions"><a className="solid-link" href="#products">Explore the platform<ArrowUpRight size={18}/></a><button className="text-link" onClick={onPitch}>The idea in 4 minutes<Play size={14}/></button></div><small>Prototype stage · Product visuals are design concepts.</small></div><figure><img src="/visuals/flagship.webp" width="1536" height="1024" fetchPriority="high" alt="Generated concept of an AMR-Eye graphite and silver microbiology workstation"/><figcaption>AMR-Eye <span>INSTRUMENT DESIGN STUDY</span></figcaption></figure></div><div className="home-branches"><a href="#pathways"><span>01 / DISCOVER</span><h2>Find your perspective.</h2><p>For investors, laboratories, institutions and the curious.</p><ArrowUpRight/></a><a href="#products"><span>02 / EXPLORE</span><h2>Meet the ecosystem.</h2><p>Hardware, software, AI and the services that connect them.</p><ArrowUpRight/></a><a href="#apex"><span>03 / GO DEEPER</span><h2>Open the library.</h2><p>83 topics. Every subsystem, use case and evidence boundary.</p><ArrowUpRight/></a></div><div className="home-recognition"><span>IDEAS PUT FORWARD.</span><a href="#recognition"><b>Bio-InnoQuest</b> Second place · HBB 2026<ArrowUpRight size={16}/></a><a href="#recognition"><b>Goa Startup Festival</b> Idea pitching · 2026<ArrowUpRight size={16}/></a></div></section>;
}

const slides=[
 {title:"A familiar method. A clearer record.",copy:"Antimicrobial susceptibility testing helps laboratories understand how a cultured organism responds to antibiotics. AMR-Eye starts with the manual measurement and fragmented records around that work.",line:"Our starting point: digital, reviewable AST.",image:"imaging",status:"Prototype direction",links:[["Understand the workflow","problem"]]},
 {title:"See. Measure. Review.",copy:"The proposed workflow captures a calibrated plate image, measures visible zones, applies a versioned standards engine and asks a qualified microbiologist to review the result. The website demonstrates these steps with synthetic data.",line:"Image → measurement → rules → human review",image:"imaging",status:"Synthetic demonstration",links:[["Try the analysis demo","demo"]]},
 {title:"One platform. The right depth.",copy:"A portable imaging pathway can grow into connected incubation and the proposed APEX XR research workstation. SaaS–BAHU connects the operator, local edge computing, instruments and optional cloud services.",line:"Modular hardware + software + support",image:"flagship",status:"Proposed product family",links:[["Explore product pathways","products"]]},
 {title:"Local insight. Shared understanding.",copy:"The longer-term vision connects validated, de-identified records to research and public-health programs. Hotspots and trends need governance and quality checks; strain and protein insights need qualified assays beyond a plate image.",line:"Laboratory → institution → national program",image:"network",status:"Future R&D",links:[["Explore the network concept","network"]]},
 {title:"An idea with momentum.",copy:"AMR-EYE received second place in Bio-InnoQuest at HBB 2026, Goa University. The project also has a Goa Startup Festival idea-pitching record. The next focus is a calibrated prototype, a reliable dataset and a supervised pilot.",line:"Recognition is a milestone. Validation is the next step.",image:"edge",status:"Project recognition & development",links:[["Meet the team","team"],["See recognition","recognition"]]},
 {title:"Help shape what comes next.",copy:"We welcome laboratories for workflow discovery, colleges and researchers for evidence building, and investors and public-health partners for the path from prototype to responsible deployment.",line:"Explore the project. Start a conversation.",image:"flagship",status:"Collaboration invitation",links:[["Contact the team","about"],["Review the roadmap","roadmap"]]}
];
export function GuidedPitch({onExit,onNavigate}:{onExit:()=>void;onNavigate:(hash:string)=>void}){
 const [index,setIndex]=useState(0);const [duration,setDuration]=useState(4);const [seconds,setSeconds]=useState(0);const [running,setRunning]=useState(false);
 useEffect(()=>{const key=(e:KeyboardEvent)=>{if((e.target as HTMLElement).matches('input,select,textarea'))return;if(e.key==='ArrowRight'){e.preventDefault();setIndex(n=>Math.min(slides.length-1,n+1))}if(e.key==='ArrowLeft'){e.preventDefault();setIndex(n=>Math.max(0,n-1))}};window.addEventListener('keydown',key);return()=>window.removeEventListener('keydown',key)},[]);
 useEffect(()=>{if(!running)return;const start=Date.now()-seconds*1000;const timer=setInterval(()=>setSeconds(Math.floor((Date.now()-start)/1000)),1000);return()=>clearInterval(timer)},[running]);
 const item=slides[index];const left=Math.max(0,duration*60-seconds);
 return <div className="guided-pitch"><header><span>AMR-Eye <b>QUICK PITCH</b></span><button onClick={onExit} aria-label="Exit quick pitch"><X/>Close</button></header><div className="pitch-tools"><label>Guide length<select value={duration} onChange={e=>{setDuration(Number(e.target.value));setSeconds(0);setRunning(false)}}><option value={3}>3 minutes</option><option value={4}>4 minutes</option><option value={5}>5 minutes</option></select></label><span aria-label="Time remaining">{Math.floor(left/60)}:{String(left%60).padStart(2,'0')}</span><button onClick={()=>setRunning(!running)}>{running?'Pause timer':'Start timer'}</button><button onClick={()=>{setIndex(0);setSeconds(0);setRunning(false)}}>Restart</button></div><div className="guided-slide" key={index}><div><small>{String(index+1).padStart(2,'0')} / {slides.length} · {item.status}</small><h2>{item.title}</h2><p>{item.copy}</p><strong>{item.line}</strong><div className="pitch-deep-links">{item.links.map(([label,hash])=><button key={hash} onClick={()=>onNavigate(hash)}>{label}<ArrowUpRight size={16}/></button>)}</div></div><figure><img src={`/visuals/${item.image}.webp`} width="1536" height="1024" alt="Generated concept illustration"/><figcaption>Illustrative concept · Not a manufactured product</figcaption></figure></div><footer><button onClick={()=>setIndex(n=>n-1)} disabled={index===0} aria-label="Previous pitch slide"><ArrowLeft/></button><nav aria-label="Pitch slides">{slides.map((s,i)=><button key={s.title} onClick={()=>setIndex(i)} aria-label={`Slide ${i+1}: ${s.title}`} aria-current={i===index?'step':undefined}>{i+1}</button>)}</nav><button onClick={()=>index===slides.length-1?onExit():setIndex(n=>n+1)}>{index===slides.length-1?'Finish':'Next'}<ArrowRight size={18}/></button></footer><small className="pitch-safety">Prototype and proposed capabilities · Synthetic demonstrations · Not for clinical use</small></div>;
}


