"use client";
import {useEffect,useState} from "react";
import {ArrowUpRight,ArrowRight,ArrowLeft,ChevronRight,Search,Menu,Play,X,BookOpen,Layers3,Microscope,Users,Compass} from "lucide-react";
import {Sheet,SheetContent,SheetHeader,SheetTitle,SheetTrigger} from "@/components/ui/sheet";
import {sectionHref} from './site-routes.mjs';
import libraryStats from './repository-stats.json';

export const directory = [
 {title:"Discover",copy:"The idea, the people, the path ahead.",links:[["Overview","home"],["The problem","problem"],["Who it is for","pathways"],["Wins & recognition","recognition"],["Our team","team"],["About & contact","about"],["The business","business"],["Roadmap","roadmap"]]},
 {title:"Explore",copy:"Products and hands-on demonstrations.",links:[["Product collection","products"],["Simulate the workflow","demo"],["Hardware concepts","hardware"],["Lab console","console"],["AMR network","network"],["Project guide","guide"],["Concept references","references"]]},
 {title:"Go deeper",copy:"Engineering, evidence and research, open to everyone.",links:[["Complete project library","library"],["Research programmes","research"],["Technology","technology"],["Imaging","imaging"],["Sensor modules","modules"],["Plate digital twin","twin"],["SaaS–BAHU","bahu"],["Architecture","architecture"],["Connectivity","integration"],["Automation","automation"],["One Health applications","applications"],["Competitive context","positioning"],["Technology glossary","wall"],["Evidence roadmap","sources"],["Development record","project-progress"]]}
];
export function SiteNavigation({active,onPitch}:{active:string;onPitch:()=>void}){
 const [open,setOpen]=useState(false);
 return <><a href="#main-content" className="skip-link" onClick={e=>{e.preventDefault();document.getElementById("main-content")?.focus()}}>Skip to content</a><header className="atelier-header"><a className="atelier-brand" href="#home"><img src="/brand/amreye-logo-white.svg" alt="AMReye.AI" width="155" height="36"/></a><nav aria-label="Primary navigation">{[["Discover","home"],["Products","products"],["Library","library"],["Team","team"]].map(([label,id])=><a key={id} href={sectionHref(id as string)} aria-current={active===id?"page":undefined}>{label}</a>)}</nav><div><button className="brief-button" onClick={onPitch}><Play size={14}/>Quick pitch</button><Sheet open={open} onOpenChange={setOpen}><SheetTrigger className="index-button" aria-label="Open site directory"><Menu size={21}/></SheetTrigger><SheetContent className="atelier-menu" aria-describedby={undefined}><SheetHeader><SheetTitle>Explore AMReye.AI.</SheetTitle></SheetHeader><p className="menu-intro">Start anywhere. Go as deep as you want.</p><div className="menu-columns">{directory.map(group=><div key={group.title}><h3>{group.title}</h3><p>{group.copy}</p><nav aria-label={group.title}>{group.links.map(([label,id])=><a key={id} href={sectionHref(id as string)} onClick={()=>setOpen(false)}>{label}<ArrowUpRight size={16}/></a>)}</nav></div>)}</div></SheetContent></Sheet></div></header><nav className="atelier-dock" aria-label="Mobile navigation">{[["Home","home",Compass],["Products","products",Layers3],["Demo","demo",Microscope],["Library","library",BookOpen]].map(([label,id,Icon])=>{const I=Icon as typeof Compass;return <a key={id as string} href={sectionHref(id as string)} aria-current={active===id?"page":undefined}><I size={19}/><span>{label as string}</span></a>})}</nav></>;
}
const stages=[
 {name:'Capture',number:'01',title:'A consistent starting point.',copy:'Calibrated plate imaging is the first step toward a reproducible measurement.',href:'/?topic=reader-v1#library',action:'Explore the reader'},
 {name:'Measure',number:'02',title:'Every zone, a traceable measure.',copy:'Explore zone diameters, calibration and corrections in the synthetic plate demonstration.',href:'#demo',action:'Simulate the workflow'},
 {name:'Review',number:'03',title:'Keep qualified people in control.',copy:'Uncertainty and unreadable results remain visible before a qualified reviewer releases a record.',href:'/?topic=plate-provenance#library',action:'Follow the review record'},
 {name:'Connect',number:'04',title:'A record with somewhere to go.',copy:'Explore the proposed path from local instruments to governed laboratory and research systems.',href:'/?topic=interoperability#library',action:'Explore connectivity'}
];
export function HomeDirectory(){
 const [stage,setStage]=useState(0),[search,setSearch]=useState(''); const current=stages[stage];
 return <section id="home" className="home-directory precision-home">
 <div className="precision-masthead"><span>Antimicrobial intelligence</span><span>Built on curiosity / Goa, India</span></div>
 <div className="precision-hero"><div className="precision-copy"><p className="hero-purpose"><strong className="ai-accent">AI</strong> for antimicrobial resistance</p><h1>Microbes.<br/><span>Huge impact.</span></h1><p className="hero-ambition">We're working toward an even greater impact for good.</p><p className="hero-description">From plate analysis to a complete microbiological record. Explore our vision for advanced instrumentation combined with AI for antimicrobial intelligence.</p><div className="hero-prototype"><span>Prototype under development</span><p>Antimicrobial susceptibility testing (AST) system prototype from Goa, India.</p></div><div className="atelier-actions"><a className="solid-link" href="#demo">Simulate the workflow<ArrowUpRight size={18}/></a></div><a className="hero-evidence" href="/library"><strong>Explore {libraryStats.topics} research topics</strong><span>Working principles &amp; microbiological breakthroughs <ArrowRight size={14}/></span></a></div>
 <figure className="precision-instrument"><img src="/visuals/flagship.webp" width="1536" height="1024" fetchPriority="high" alt="Illustration of the APEX XR antimicrobial intelligence workstation design, with a plate imaging chamber"/><figcaption><span className="flagship-name">Antimicrobial Intelligence<br/>Workstation<small>APEX XR</small></span><span className="flagship-stage">Advanced R&amp;D direction<br/>Design illustration</span></figcaption></figure></div>
 <div className="precision-workflow"><div className="workflow-heading"><span className="eyebrow">The workflow</span><p>Trust the process.<br/>Follow the evidence.</p></div><div className="workflow-interaction"><div className="workflow-tabs" role="tablist" aria-label="Plate workflow">{stages.map((s,i)=><button id={'stage-'+i} key={s.name} role="tab" aria-selected={stage===i} aria-controls="workflow-panel" tabIndex={stage===i?0:-1} onClick={()=>setStage(i)} onKeyDown={e=>{let n=i;if(e.key==='ArrowRight')n=(i+1)%4;else if(e.key==='ArrowLeft')n=(i+3)%4;else if(e.key==='Home')n=0;else if(e.key==='End')n=3;else return;e.preventDefault();setStage(n);document.getElementById('stage-'+n)?.focus()}}><small>{s.number}</small>{s.name}</button>)}</div><div id="workflow-panel" role="tabpanel" aria-labelledby={'stage-'+stage} className="workflow-panel"><div><h2>{current.title}</h2><p>{current.copy}</p><a href={current.href}>{current.action}<ArrowUpRight size={18}/></a></div></div></div></div>
 <div className="precision-index-heading"><h2>Explore the project.</h2><form className="home-search" role="search" onSubmit={e=>{e.preventDefault();location.href='/library?q='+encodeURIComponent(search)}}><Search size={18}/><input aria-label="Search all project knowledge" value={search} onChange={e=>setSearch(e.target.value)} placeholder="Search the project…"/><button aria-label="Search project"><ArrowRight size={19}/></button></form></div>
 <div className="home-branches"><a href="#products"><span>01 / Instruments &amp; platform</span><h2>Instruments &amp; platform.</h2><p>From a portable reader prototype to advanced research workstation pathways.</p><ArrowUpRight/></a><a href="/library"><span>02 / Antimicrobial intelligence</span><h2>Follow your curiosity.</h2><p>The complete technical, microbiological and AI topic library.</p><ArrowUpRight/></a><a href="#pathways"><span>03 / Collaboration</span><h2>Connect with our vision.</h2><p>For laboratories, researchers, institutions and investors.</p><ArrowUpRight/></a></div>
 <div className="home-recognition"><span>Project milestones</span><a href="#recognition"><b>Bio-InnoQuest</b> Second place · HBB 2026<ArrowUpRight size={16}/></a><a href="#recognition"><b>PU EPIC</b> Pre-incubation selection · GSF 2026<ArrowUpRight size={16}/></a></div></section>;
}

const slides=[
 {title:"A familiar method. A clearer record.",copy:"Antimicrobial susceptibility testing helps laboratories understand how a cultured organism responds to antibiotics. AMReye.AI starts with the manual measurement and fragmented records around that work.",line:"Our starting point: digital, reviewable AST.",image:"imaging",status:"Prototype direction",links:[["Understand the workflow","problem"]]},
 {title:"See. Measure. Review.",copy:"The proposed workflow captures a calibrated plate image, measures visible zones, applies a versioned standards engine and asks a qualified microbiologist to review the result. The website demonstrates these steps with synthetic data.",line:"Image → measurement → rules → human review",image:"imaging",status:"Synthetic demonstration",links:[["Try the analysis demo","demo"]]},
 {title:"One platform. The right depth.",copy:"A portable imaging pathway can grow into connected incubation and the proposed APEX XR research workstation. SaaS–BAHU connects the operator, local edge computing, instruments and optional cloud services.",line:"Modular hardware + software + support",image:"flagship",status:"Proposed product family",links:[["Explore product pathways","products"]]},
 {title:"Local insight. Shared understanding.",copy:"The longer-term vision connects validated, de-identified records to research and public-health programs. Hotspots and trends need governance and quality checks; strain and protein insights need qualified assays beyond a plate image.",line:"Laboratory → institution → national program",image:"network",status:"Future R&D",links:[["Explore the network concept","network"]]},
 {title:"An idea with momentum.",copy:"AMReye.AI received second place in Bio-InnoQuest at HBB 2026, Goa University. The project was also selected for PU EPIC pre-incubation following Goa Startup Festival 2026. The next focus is a calibrated prototype, a reliable dataset and a supervised pilot.",line:"Recognition is a milestone. Validation is the next step.",image:"edge",status:"Project recognition & development",links:[["Meet the team","team"],["See recognition","recognition"]]},
 {title:"Help shape what comes next.",copy:"We welcome laboratories for workflow discovery, colleges and researchers for evidence building, and investors and public-health partners for the path from prototype to responsible deployment.",line:"Explore the project. Start a conversation.",image:"flagship",status:"Collaboration invitation",links:[["Contact the team","about"],["Review the roadmap","roadmap"]]}
];
export function GuidedPitch({onExit,onNavigate}:{onExit:()=>void;onNavigate:(hash:string)=>void}){
 const [index,setIndex]=useState(0);useEffect(()=>{const n=Number(new URLSearchParams(location.search).get('slide'));if(n>=1&&n<=slides.length)setIndex(n-1)},[]);const choose=(n:number)=>{setIndex(n);const u=new URL(location.href);u.searchParams.set('slide',String(n+1));history.replaceState({},'',u)};const [duration,setDuration]=useState(4);const [seconds,setSeconds]=useState(0);const [running,setRunning]=useState(false);
 useEffect(()=>{const key=(e:KeyboardEvent)=>{if((e.target as HTMLElement).closest('input,select,textarea,[contenteditable=true]'))return;if(e.key==='Escape'){onExit();return}if(e.key==='ArrowRight'){e.preventDefault();choose(Math.min(slides.length-1,index+1))}if(e.key==='ArrowLeft'){e.preventDefault();choose(Math.max(0,index-1))}};window.addEventListener('keydown',key);return()=>window.removeEventListener('keydown',key)},[index,onExit]);
 useEffect(()=>{if(!running)return;const start=Date.now()-seconds*1000;const timer=setInterval(()=>setSeconds(Math.floor((Date.now()-start)/1000)),1000);return()=>clearInterval(timer)},[running]);
 useEffect(()=>{if(running&&seconds>=duration*60)setRunning(false)},[running,seconds,duration]);
 const item=slides[index];const left=Math.max(0,duration*60-seconds);
 return <div className="guided-pitch"><header><span>AMReye.AI <b>QUICK PITCH</b></span><button onClick={onExit} aria-label="Exit quick pitch"><X/>Close</button></header><div className="pitch-tools"><label>Guide length<select value={duration} onChange={e=>{setDuration(Number(e.target.value));setSeconds(0);setRunning(false)}}><option value={3}>3 minutes</option><option value={4}>4 minutes</option><option value={5}>5 minutes</option></select></label><span aria-label="Time remaining" role="timer">{Math.floor(left/60)}:{String(left%60).padStart(2,'0')}</span><button onClick={()=>setRunning(!running)}>{running?'Pause timer':'Start timer'}</button><button onClick={()=>{choose(0);setSeconds(0);setRunning(false)}}>Restart</button></div><div className="guided-slide" key={index}><div><small>{String(index+1).padStart(2,'0')} / {slides.length} · {item.status}</small><h2>{item.title}</h2><p>{item.copy}</p><strong>{item.line}</strong><div className="pitch-deep-links">{item.links.map(([label,hash])=><button key={hash} onClick={()=>onNavigate(hash)}>{label}<ArrowUpRight size={16}/></button>)}</div></div><div className="pitch-stage-map" aria-label="Presentation progress">{slides.map((s,i)=><button key={s.title} className={i===index?"current":""} onClick={()=>choose(i)}><span>{i+1}</span><b>{["Problem","Measurement","Platform","Public health","Progress","Collaboration"][i]}</b></button>)}</div></div><footer><button onClick={()=>choose(index-1)} disabled={index===0} aria-label="Previous pitch slide"><ArrowLeft/></button><nav aria-label="Pitch slides">{slides.map((s,i)=><button key={s.title} onClick={()=>choose(i)} aria-label={`Slide ${i+1}: ${s.title}`} aria-current={i===index?'step':undefined}>{i+1}</button>)}</nav><button onClick={()=>index===slides.length-1?onExit():choose(index+1)}>{index===slides.length-1?'Finish':'Next'}<ArrowRight size={18}/></button></footer><small className="pitch-safety">Prototype and proposed capabilities · Synthetic demonstrations · Not for clinical use</small></div>;
}


