"use client";
import {useEffect,useState} from 'react';
import {regions,organisms,antibiotics,periods,defaultMapState,restoreMapState,regionMetric} from './network-data.mjs';
type View='india'|'global';
const SYNTHETIC='Synthetic demonstration, not live surveillance';
// Schematic outlines locate selectable regions. They are not jurisdictional boundaries.
const indiaPath='M241 38 L280 54 303 44 318 69 303 89 321 111 336 144 377 167 422 157 467 177 459 199 426 188 408 211 376 225 355 254 325 271 310 313 287 350 273 402 253 419 235 387 215 340 197 301 185 265 162 239 145 220 166 206 191 217 195 193 215 174 219 140 199 120 216 103 208 76 Z';
const worldPaths=['M45 78 L100 51 150 59 180 88 157 122 172 157 146 183 121 169 98 135 69 119 Z','M163 210 L202 216 236 258 221 312 193 374 172 326 161 277 145 236 Z','M265 83 L300 64 344 87 350 121 325 148 284 131 Z','M280 157 L327 154 363 190 366 234 335 297 314 319 290 274 268 230 262 192 Z','M349 72 L415 51 476 63 547 92 568 139 525 173 501 209 455 188 439 236 415 242 394 200 379 164 347 144 Z','M461 290 L501 278 538 307 528 345 489 352 460 322 Z','M555 340 L568 322 574 330 565 353 Z'];
export default function NetworkExplorer(){
 const [state,setState]=useState<{view:string;selection:Record<View,string>;organism:string;antibiotic:string;period:string}>(defaultMapState);const [restored,setRestored]=useState(false);
 useEffect(()=>{try{setState(()=>{const saved=restoreMapState(JSON.parse(sessionStorage.getItem('amr-map-v1')||'null'));return {...saved,selection:{india:saved.selection.india,global:saved.selection.global}}})}catch{}setRestored(true)},[]);
 useEffect(()=>{if(restored)try{sessionStorage.setItem('amr-map-v1',JSON.stringify(state))}catch{}},[state,restored]);
 const view=state.view as View;const list=regions[view];const selected=state.selection[view];const current=list.find(r=>r.id===selected)!;const metric=regionMetric(selected,state);
 const choose=(id:string)=>setState(s=>({...s,selection:{...s.selection,[view]:id}}));
 return <div className="amr-map-panel"><div className="map-toolbar"><div className="view-switch" aria-label="Map view">{(['india','global'] as const).map(v=><button key={v} aria-pressed={view===v} onClick={()=>setState(s=>({...s,view:v}))}>{v==='india'?'India':'Global'}</button>)}</div><p>{SYNTHETIC}</p><div className="map-filters"><label>Organism<select value={state.organism} onChange={e=>setState(s=>({...s,organism:e.target.value}))}>{Object.entries(organisms).map(([id,label])=><option value={id} key={id}>{label}</option>)}</select></label><label>Antibiotic<select value={state.antibiotic} onChange={e=>setState(s=>({...s,antibiotic:e.target.value}))}>{Object.entries(antibiotics).map(([id,label])=><option value={id} key={id}>{label}</option>)}</select></label><label>Reporting period<select value={state.period} onChange={e=>setState(s=>({...s,period:e.target.value}))}>{periods.map(p=><option key={p}>{p}</option>)}</select></label></div></div>
 <div className="map-workspace"><div className="map-visual"><svg viewBox="0 0 600 450" role="group" aria-label={`${view==='india'?'India':'Global'} synthetic AMR map. Select a region or use the list below.`}>
 <g className="map-grid" aria-hidden="true">{[100,200,300,400,500].map(x=><line key={x} x1={x} x2={x} y1="20" y2="430"/>)}{[100,200,300,400].map(y=><line key={y} y1={y} y2={y} x1="20" x2="580"/>)}</g>
 <g className="map-land" aria-hidden="true">{(view==='india'?[indiaPath]:worldPaths).map((d,i)=><path d={d} key={i}/>)}</g>
 {list.map((r,i)=>{const m=regionMetric(r.id,state);return <g className="region-marker" data-region={r.id} role="button" tabIndex={0} key={r.id} aria-pressed={selected===r.id} aria-label={`Select ${r.name}: ${m.percent===null?'No example data':m.percent.toFixed(1)+'% synthetic resistance'}`} onClick={()=>choose(r.id)} onKeyDown={e=>{if(e.key==='Enter'||e.key===' '){e.preventDefault();choose(r.id)}}}><circle cx={r.x} cy={r.y} r="28" fill="transparent"/><circle cx={r.x} cy={r.y} r={selected===r.id?17:13} className={m.percent===null?'marker-empty':'marker-dot'}/><text x={r.x} y={r.y+4} textAnchor="middle">{i+1}</text></g>})}
 </svg><p className="map-caption">Schematic geography. Numbered markers match the region list; boundaries are illustrative.</p>
 <div className="region-list" aria-label="Equivalent accessible region list">{list.map((r,i)=>{const m=regionMetric(r.id,state);return <button key={r.id} data-region={r.id} aria-pressed={selected===r.id} onClick={()=>choose(r.id)}><span>{i+1}</span><b>{r.name}</b><small>{m.percent===null?'No example data':`${m.percent.toFixed(1)}%`}</small></button>})}</div></div>
 <div className="selected-region" role="status" aria-live="polite"><small>{SYNTHETIC}</small><h3>{current.name}</h3><p>{organisms[state.organism as keyof typeof organisms]} · {antibiotics[state.antibiotic as keyof typeof antibiotics]}<br/>{state.period}</p>{metric.percent===null?<div className="map-empty"><b>No example data</b><p>No valid tested count for this selection. A resistance proportion cannot be calculated.</p></div>:<><div className="resistance-value">{metric.percent.toFixed(1)}<span>%</span></div><p>Example resistance proportion</p><dl><div><dt>Tested examples</dt><dd>{metric.tested}</dd></div><div><dt>Resistant examples</dt><dd>{metric.resistant}</dd></div><div><dt>Trend</dt><dd>{metric.trend===null?'Not available':`${metric.trend>0?'+':''}${metric.trend.toFixed(1)} pp`}</dd></div></dl><p className="map-calculation">{metric.resistant} ÷ {metric.tested} × 100. {metric.previousPeriod?`Trend versus ${metric.previousPeriod}, in percentage points.`:'No earlier period in this fixture.'}</p></>}<p>Invented, fixed counts for interaction only. Global regions are independent examples, not a combined global estimate. AMR-Eye does not operate a live surveillance network.</p><nav><a href="?topic=research-surveillance#apex">Surveillance research ↗</a><a href="?topic=research-models#apex">Dataset governance ↗</a></nav></div></div></div>;
}
