"use client";

import { useEffect, useMemo, useState } from "react";
import type { CSSProperties } from "react";
import {
  Activity, BarChart3, Beaker, Bot, Box, BrainCircuit, Check, ChevronRight,
  CircleGauge, Cloud, Database, FlaskConical, Gauge, HeartPulse, Menu,
  Microscope, Play, Radio, ScanLine, Server, ShieldCheck, Sparkles,
  Thermometer, UserCheck, WifiOff, X, Zap,
} from "lucide-react";
import { Accordion, AccordionContent, AccordionItem, AccordionTrigger } from "@/components/ui/accordion";
import { Dialog, DialogContent, DialogHeader, DialogTitle } from "@/components/ui/dialog";
import { Progress } from "@/components/ui/progress";
import { Sheet, SheetContent, SheetHeader, SheetTitle, SheetTrigger } from "@/components/ui/sheet";
import { Slider } from "@/components/ui/slider";
import { Switch } from "@/components/ui/switch";
import { Table, TableBody, TableCell, TableHead, TableHeader, TableRow } from "@/components/ui/table";

type Scope = "Prototype demo" | "Proposed product" | "Future R&D";
type Illumination = "Trans" | "Epi" | "Oblique" | "NIR";
type Antibiotic = { code: string; name: string; mm: number; confidence: number; result: "S" | "I" | "R"; x: number; y: number; zone: number; };

const antibiotics: Antibiotic[] = [
  { code: "AMP", name: "Ampicillin", mm: 11.8, confidence: 96.1, result: "R", x: 30, y: 27, zone: 21 },
  { code: "CIP", name: "Ciprofloxacin", mm: 25.4, confidence: 98.7, result: "S", x: 69, y: 29, zone: 35 },
  { code: "GEN", name: "Gentamicin", mm: 18.6, confidence: 97.4, result: "I", x: 34, y: 70, zone: 28 },
  { code: "CTX", name: "Cefotaxime", mm: 27.1, confidence: 98.2, result: "S", x: 70, y: 69, zone: 37 },
];

const analysisStages = ["Detecting plate", "Calibrating plate diameter", "Detecting antibiotic discs", "Segmenting inhibition zones", "Measuring zone diameters", "Applying standards engine", "Generating output"];
const navItems = [["Home", "home"], ["Technology", "technology"], ["Live Demo", "demo"], ["BAHU", "bahu"], ["Architecture", "architecture"], ["Applications", "applications"], ["Business", "business"], ["Roadmap", "roadmap"], ["About", "about"]];
const techWall: Record<string, string> = {
  RAST: "Rapid AST workflows are a future research and validation direction.",
  MIC: "A proposed broth-microdilution module for direct minimum inhibitory concentration measurement.",
  NIR: "An experimental 940 nm channel for difficult optical conditions, including condensation.",
  VOC: "Auxiliary metabolic sensing; not a standalone organism identification method.",
  LiDAR: "Experimental coarse depth, positioning and morphology data.",
  "Sensor Fusion": "Combines vision, kinetics, VOC and environmental context with confidence controls.",
  "Digital Twin": "A traceable, time-stamped digital record for every plate.",
  Robotics: "Future handling and workflow automation modules.",
  "Edge AI": "Local vision processing for lower latency, privacy and offline operation.",
  LIMS: "Laboratory Information Management System connectivity.", LIS: "Laboratory Information System connectivity.",
  CLSI: "Clinical and Laboratory Standards Institute rule source.", EUCAST: "European Committee on Antimicrobial Susceptibility Testing rule source.",
  "One Health": "Potential use across human, animal, food and environmental sectors.",
  "AMR Heatmap": "A future anonymized, governed resistance-surveillance interface.",
  SaaS: "Recurring software, standards, analytics and fleet-service layer.",
  BAHU: "Bio-Automation & Human User Interface: the human-facing lab control layer.",
  "Custom Automation": "Lab audit, SOP mapping and modular deployment around existing workflows.",
  "Human-in-the-Loop": "A qualified laboratory professional validates or changes the system suggestion.",
};

function ScopeTag({ children }: { children: Scope }) {
  const cls = children === "Prototype demo" ? "scope-current" : children === "Proposed product" ? "scope-proposed" : "scope-future";
  return <span className={`scope-tag ${cls}`}>{children}</span>;
}

function SectionTitle({ eyebrow, title, copy, scope }: { eyebrow: string; title: string; copy?: string; scope?: Scope }) {
  return <div className="section-heading"><div className="section-kicker"><span>{eyebrow}</span>{scope && <ScopeTag>{scope}</ScopeTag>}</div><h2>{title}</h2>{copy && <p>{copy}</p>}</div>;
}

function Flow({ items, compact = false }: { items: string[]; compact?: boolean }) {
  return <div className={`flow ${compact ? "flow-compact" : ""}`}>{items.map((item, i) => <div className="flow-unit" key={item}><span>{item}</span>{i < items.length - 1 && <ChevronRight aria-hidden="true" />}</div>)}</div>;
}

function Plate({ analyzed, selected, mode, compact = false }: { analyzed: boolean; selected: string; mode: string; compact?: boolean }) {
  return <div className={`plate-wrap ${compact ? "plate-compact" : ""}`}><div className={`plate mode-${mode.toLowerCase()}`} aria-label="Synthetic Kirby-Bauer antimicrobial susceptibility test plate"><div className="lawn-texture" />{antibiotics.map((a) => {
    const active = selected === a.code;
    return <button aria-label={`${a.code}, ${a.mm} millimetre inhibition zone`} className={`zone ${active ? "zone-active" : ""} ${analyzed ? "zone-analyzed" : ""}`} key={a.code} style={{ left: `${a.x}%`, top: `${a.y}%`, width: `${a.zone}%`, aspectRatio: "1" }} type="button"><span className="disc">{a.code}</span>{analyzed && <><span className="diameter-line" /><span className="measure">{a.mm} mm</span></>}</button>;
  })}{analyzed && <span className="plate-detected">PLATE Ø 90.0 MM · DETECTED</span>}<span className="scan-sweep" /></div><div className="plate-corners" aria-hidden="true"><i /><i /><i /><i /></div></div>;
}

function AnalysisDemo({ pitch = false, onArchitecture }: { pitch?: boolean; onArchitecture?: () => void }) {
  const [stage, setStage] = useState(-1); const [selected, setSelected] = useState("CIP"); const [review, setReview] = useState("Awaiting review");
  const running = stage >= 0 && stage < analysisStages.length; const complete = stage >= analysisStages.length;
  const run = () => { if (!running) { setStage(0); setReview("Awaiting review"); } };
  useEffect(() => { if (!running) return; const timer = window.setTimeout(() => setStage((s) => s + 1), pitch ? 420 : 520); return () => window.clearTimeout(timer); }, [stage, running, pitch]);
  const progress = stage < 0 ? 0 : Math.min(100, (stage / analysisStages.length) * 100);
  return <div className={`analysis-shell ${pitch ? "pitch-shell" : ""}`}><div className="analysis-toolbar"><div><span className="live-dot" /> AMR-EYE VISION · SAMPLE AST-2409-017</div><span className="demo-chip">SYNTHETIC PLATE</span></div><div className="analysis-grid"><div className="plate-panel"><div className="panel-label"><ScanLine /> LIVE OPTICAL VIEW <span>TRANS · RGB</span></div><Plate analyzed={complete} selected={selected} mode="trans" compact={pitch} /><div className="analysis-progress"><div><span>{stage < 0 ? "Ready for deterministic analysis" : complete ? "Analysis complete" : analysisStages[stage]}</span><b>{Math.round(progress)}%</b></div><Progress value={progress} /></div><button className="primary-action run-button" onClick={run} disabled={running}>{running ? <Activity className="spin-soft" /> : complete ? <Check /> : <Play />}{running ? "ANALYSIS RUNNING" : complete ? "RUN AGAIN" : "RUN AMR-EYE ANALYSIS"}</button></div><div className="results-panel"><div className="panel-label"><BarChart3 /> ANALYSIS OUTPUT <span>{complete ? "7/7 STAGES" : "STANDBY"}</span></div><div className="stage-list">{analysisStages.map((item, i) => <span key={item} className={stage > i ? "done" : stage === i ? "active" : ""}><i>{stage > i ? "✓" : i + 1}</i>{item}</span>)}</div><Table className="results-table"><TableHeader><TableRow><TableHead>ANTIBIOTIC</TableHead><TableHead>ZONE</TableHead><TableHead>CONF.</TableHead><TableHead>S/I/R</TableHead></TableRow></TableHeader><TableBody>{antibiotics.map((a) => <TableRow key={a.code} data-state={selected === a.code ? "selected" : undefined} onClick={() => setSelected(a.code)}><TableCell><button type="button" onClick={() => setSelected(a.code)}><b>{a.code}</b><small>{a.name}</small></button></TableCell><TableCell>{complete ? `${a.mm} mm` : "—"}</TableCell><TableCell>{complete ? `${a.confidence}%` : "—"}</TableCell><TableCell>{complete ? <span className={`sir sir-${a.result.toLowerCase()}`}>{a.result}</span> : "—"}</TableCell></TableRow>)}</TableBody></Table><p className="micro-disclaimer">Simulated demonstration data. CLSI/EUCAST interpretation shown for interface demonstration only.</p>{complete && <div className="review-card"><div><UserCheck /><span>HUMAN REVIEW</span><b className={`review-${review.toLowerCase().replaceAll(" ", "-")}`}>{review}</b></div><p>Measured zone: <strong>{antibiotics.find((a) => a.code === selected)?.mm} mm</strong> · AI confidence: <strong>{antibiotics.find((a) => a.code === selected)?.confidence}%</strong></p><div className="review-actions"><button onClick={() => setReview("Approved")}><Check /> Approve</button><button onClick={() => setReview("Edited")}>Edit</button><button onClick={() => setReview("Rejected")}><X /> Reject</button></div></div>}{pitch && onArchitecture && <button className="secondary-action full-width" onClick={onArchitecture}>View Full Platform Architecture <ChevronRight /></button>}</div></div></div>;
}

function MiniChart() { return <svg className="voc-chart" viewBox="0 0 500 180" role="img" aria-label="Simulated volatile organic compound sensor response over time"><defs><linearGradient id="voc-fill" x1="0" x2="0" y1="0" y2="1"><stop offset="0" stopColor="#35f2df" stopOpacity=".38"/><stop offset="1" stopColor="#35f2df" stopOpacity="0"/></linearGradient></defs>{[30,70,110,150].map((y) => <line key={y} x1="35" x2="480" y1={y} y2={y} stroke="rgba(142,211,215,.14)" />)}<path d="M35 145 C75 145, 82 132, 118 134 S175 108, 208 115 S263 72, 301 88 S348 50, 385 64 S433 29, 480 41 L480 165 L35 165Z" fill="url(#voc-fill)" /><path d="M35 145 C75 145, 82 132, 118 134 S175 108, 208 115 S263 72, 301 88 S348 50, 385 64 S433 29, 480 41" fill="none" stroke="#35f2df" strokeWidth="3" /><text x="35" y="176">0h</text><text x="245" y="176">12h</text><text x="450" y="176">24h</text></svg>; }

function LabConsole() {
  const [temperature, setTemperature] = useState([37]); const [interval, setIntervalValue] = useState([15]); const [illumination, setIllumination] = useState<Illumination>("Trans");
  return <div className="console-shell" id="console"><div className="console-topbar"><div><span className="live-dot" /> DEVICE AMR-CORE-01</div><span>LOCAL EDGE MODE · SYNC READY</span></div><div className="console-grid">
    <article className="console-card primary-console"><div className="card-head"><Thermometer /> BIO-VAULT <ScopeTag>Proposed product</ScopeTag></div><strong>{temperature[0].toFixed(1)} °C</strong><small>TARGET TEMPERATURE</small><Slider min={34} max={40} step={0.1} value={temperature} onValueChange={setTemperature} /><div className="metric-row"><span>Humidity <b>61%</b></span><span>Incubation <b className="ok">ACTIVE</b></span><span>Door <b>CLOSED</b></span></div></article>
    <article className="console-card"><div className="card-head"><ScanLine /> VISION</div><strong>{illumination}</strong><small>ILLUMINATION MODE</small><div className="toggle-strip">{(["Trans", "Epi", "Oblique", "NIR"] as Illumination[]).map((x) => <button className={illumination === x ? "active" : ""} onClick={() => setIllumination(x)} key={x}>{x}</button>)}</div><div className="metric-row"><span>RGB <b className="ok">ON</b></span><span>Exposure <b>1/60</b></span></div></article>
    <article className="console-card"><div className="card-head"><Microscope /> AST</div><strong>04</strong><small>DISCS DETECTED</small><div className="metric-row"><span>Plate <b className="ok">LOCKED</b></span><span>Status <b>READY</b></span></div><Progress value={82} /></article>
    <article className="console-card"><div className="card-head"><Gauge /> SENSORS <ScopeTag>Future R&D</ScopeTag></div><div className="sensor-list"><span>Temperature <b>37.0 °C</b></span><span>Humidity <b>61%</b></span><span>VOC <b>SIM</b></span><span>Depth <b>SIM</b></span><span>Device health <b className="ok">98%</b></span></div></article>
    <article className="console-card"><div className="card-head"><BrainCircuit /> EDGE AI</div><strong>YOLO-CV · DEMO</strong><small>LOCAL MODEL PROFILE</small><div className="metric-row"><span>Queue <b>01</b></span><span>Mean confidence <b>97.6%</b></span></div></article>
    <article className="console-card"><div className="card-head"><Database /> STANDARDS</div><strong>DEMO DB</strong><small>VERSION-CONTROLLED RULE LAYER</small><div className="metric-row"><span>CLSI <b>MOCK 2026</b></span><span>EUCAST <b>MOCK 16.0</b></span></div></article>
    <article className="console-card wide"><div className="card-head"><Bot /> AUTOMATION <ScopeTag>Proposed product</ScopeTag></div><div className="workflow-status"><div><small>CURRENT WORKFLOW</small><b>AST time-lapse acquisition</b></div><div><small>NEXT OPERATION</small><b>Capture frame · 00:12:41</b></div><Progress value={64} /></div></article>
    <article className="console-card wide"><div className="card-head"><CircleGauge /> CONTROL PARAMETERS</div><label>Imaging interval <b>{interval[0]} min</b></label><Slider min={5} max={60} step={5} value={interval} onValueChange={setIntervalValue} /><div className="switch-row"><label><Switch defaultChecked /> Auto-analysis</label><label><Switch defaultChecked /> QC flagging</label><label><Switch /> Cloud sync</label></div><small>All controls are simulated for product demonstration.</small></article>
  </div></div>;
}

export default function Home() {
  const [pitchMode, setPitchMode] = useState(false); const [illumination, setIllumination] = useState<Illumination>("Trans"); const [selectedTech, setSelectedTech] = useState<string | null>(null); const [showArchitecture, setShowArchitecture] = useState(false); const [installPrompt, setInstallPrompt] = useState<Event | null>(null);
  useEffect(() => { if ("serviceWorker" in navigator) navigator.serviceWorker.register("/sw.js").catch(() => undefined); const handler = (e: Event) => { e.preventDefault(); setInstallPrompt(e); }; window.addEventListener("beforeinstallprompt", handler); return () => window.removeEventListener("beforeinstallprompt", handler); }, []);
  const install = async () => { const p = installPrompt as Event & { prompt?: () => Promise<void> }; if (p?.prompt) await p.prompt(); };
  const illuminationCopy = useMemo(() => ({ Trans: "Zone boundaries, silhouettes and quantitative measurement", Epi: "Surface appearance, pigmentation and visible morphology", Oblique: "Surface texture, colony edges and shadow-enhanced morphology", NIR: "Experimental 940 nm channel for difficult optical conditions" }[illumination]), [illumination]);
  return <main className={pitchMode ? "pitch-active" : ""}>
    <header className="site-header"><a href="#home" className="brand"><img src="/amr-eye-icon.png" alt="AMR-Eye app icon" /><span><b>AMR-EYE</b><i>.AI</i></span></a><nav aria-label="Primary navigation">{navItems.map(([label, id]) => <a href={`#${id}`} key={id}>{label}</a>)}</nav><div className="header-actions"><button className="pitch-button" onClick={() => setPitchMode(true)}><Sparkles /> Pitch Mode</button><a className="console-button" href="#console">Launch Lab Console</a><Sheet><SheetTrigger className="mobile-menu" aria-label="Open navigation"><Menu /></SheetTrigger><SheetContent className="mobile-sheet"><SheetHeader><SheetTitle>AMR-EYE.AI</SheetTitle></SheetHeader><nav>{navItems.map(([label,id]) => <a href={`#${id}`} key={id}>{label}<ChevronRight /></a>)}</nav></SheetContent></Sheet></div></header>

    <section className="hero" id="home"><div className="hero-grid-bg" /><div className="hero-copy"><div className="status-line"><span className="live-dot" /> RESEARCH / PROTOTYPE DEMONSTRATION — NOT FOR CLINICAL USE</div><div className="hero-brand"><img src="/amr-eye-icon.png" alt="AMR-Eye Petri Eye logo" /><span>AMR-EYE.AI</span></div><h1>From Petri Dish to <span>Digital Intelligence.</span></h1><p>AI-assisted antimicrobial susceptibility testing and modular bio-automation for the laboratories of the future.</p><div className="hero-actions"><button className="primary-action" onClick={() => document.querySelector("#demo")?.scrollIntoView({ behavior: "smooth" })}><Play /> Launch Live Demo</button><a className="secondary-action" href="#technology">Explore Technology <ChevronRight /></a></div><div className="hero-proof"><span><b>AST-FIRST</b>Focused MVP</span><span><b>EDGE-CAPABLE</b>Offline pathway</span><span><b>HUMAN-IN-LOOP</b>Final control</span></div></div><div className="hero-visual"><div className="orbital-plate"><img src="/amr-eye-icon.png" alt="" /><span className="orbit one"><i>VISION</i></span><span className="orbit two"><i>STANDARDS</i></span><span className="orbit three"><i>BAHU</i></span></div><div className="system-readout"><span>SYSTEM STATUS</span><b><i className="live-dot" /> DEMO READY</b><small>Local deterministic pipeline</small></div></div><div className="hero-flow"><Flow items={["Culture Plate", "Vision", "AI", "Standards", "Verified Result"]} /><p>AMR-Eye starts with AST. The architecture is designed to evolve into an AI-native laboratory operating system.</p></div></section>

    <section className="section problem-section"><SectionTitle eyebrow="01 · THE PROBLEM" title="A proven method. A fragmented workflow." copy="Kirby–Bauer AST remains scientifically useful. The opportunity is to make its measurement, traceability and review more consistent." /><div className="problem-grid"><div className="problem-list">{["Manual zone measurement", "Observer variability", "Fragmented equipment", "Delayed interpretation", "Manual documentation", "Limited continuous monitoring", "Disconnected lab systems"].map((x, i) => <div key={x}><span>0{i + 1}</span><p>{x}</p></div>)}</div><div className="compare-card"><div><small>TRADITIONAL WORKFLOW</small><Flow compact items={["Plate", "Manual ruler", "Lookup", "Paper report"]} /></div><div className="digital-flow"><small>AMR-EYE DIGITAL WORKFLOW</small><Flow compact items={["Calibrated image", "AI measure", "Rules engine", "Human verify", "Digital report"]} /></div><p><ShieldCheck /> Designed to assist validated microbiology—not bypass it.</p></div></div></section>
    <section className="section demo-section" id="demo"><SectionTitle eyebrow="02 · LIVE PRODUCT DEMO" title="See the plate become structured data." copy="A deterministic synthetic analysis built for a reliable live pitch." scope="Prototype demo" /><AnalysisDemo /></section>

    <section className="section technology-section" id="technology"><SectionTitle eyebrow="03 · MEASURE → INTERPRET → VALIDATE" title="The AI does not invent breakpoints." copy="Optical measurement, structured rules and professional validation remain distinct." /><div className="standards-quote"><BrainCircuit /><span>“The AI measures. The standards engine interprets. The microbiologist validates.”</span></div><div className="technology-grid"><article className="glass-card sir-card"><div className="card-head"><ShieldCheck /> S / I / R EXPLAINED</div><Accordion type="single" collapsible defaultValue="S"><AccordionItem value="S"><AccordionTrigger><span className="sir sir-s">S</span> Susceptible</AccordionTrigger><AccordionContent>Likely inhibited by the antimicrobial at the exposure represented by the selected standard and test conditions.</AccordionContent></AccordionItem><AccordionItem value="I"><AccordionTrigger><span className="sir sir-i">I</span> Standard-dependent terminology</AccordionTrigger><AccordionContent><b>CLSI:</b> Intermediate. <b>EUCAST:</b> Susceptible, Increased Exposure. The interface must display the active standard and version.</AccordionContent></AccordionItem><AccordionItem value="R"><AccordionTrigger><span className="sir sir-r">R</span> Resistant</AccordionTrigger><AccordionContent>Not inhibited at the defined breakpoint under the selected standard and method.</AccordionContent></AccordionItem></Accordion><p>The computer-vision layer measures the optical result. Version-controlled rules perform the S/I/R mapping.</p></article><article className="glass-card standards-card"><div className="card-head"><Database /> STANDARDS ENGINE <ScopeTag>Proposed product</ScopeTag></div><div className="standard-fields">{[["Organism","E. coli · DEMO"],["Antibiotic","Ciprofloxacin"],["Method","Disk diffusion"],["Zone diameter","25.4 mm"],["MIC","Not measured"],["Standard","EUCAST / CLSI demo"],["Version","Mock 2026"],["Breakpoint","Interface only"],["Interpretation","S · suggested"],["QC status","Human review"]].map(([k,v]) => <div key={k}><small>{k}</small><b>{v}</b></div>)}</div><Flow compact items={["AI Measurement", "Structured Standards DB", "S/I/R Rule", "Human Verification"]} /></article></div></section>

    <section className="section imaging-section"><SectionTitle eyebrow="04 · MULTI-MODE IMAGING" title="One plate. Multiple optical perspectives." copy="Mode switching below changes the synthetic optical view." scope="Proposed product" /><div className="imaging-grid"><div><Plate analyzed selected="CIP" mode={illumination} /></div><div className="mode-controls">{(["Trans","Epi","Oblique","NIR"] as Illumination[]).map((mode) => <button key={mode} onClick={() => setIllumination(mode)} className={illumination === mode ? "active" : ""}><span>{mode === "NIR" ? "940 NM" : `${mode.toUpperCase()}-ILLUMINATION`}</span><p>{{Trans:"Zone metrology",Epi:"Surface morphology",Oblique:"Texture + edges",NIR:"Fog vision · experimental"}[mode]}</p>{mode === "NIR" && <ScopeTag>Future R&D</ScopeTag>}</button>)}<div className="mode-detail"><ScanLine /><div><small>ACTIVE OPTICAL PURPOSE</small><b>{illuminationCopy}</b></div></div></div></div></section>

    <section className="section modules-section"><SectionTitle eyebrow="05 · MODULAR SCIENCE" title="Standardize first. Add sensing with evidence." copy="Advanced channels are separated from the AST demo and clearly marked as proposed or experimental." /><div className="module-grid"><article className="glass-card mic-card"><div className="card-head"><Beaker /> MIC MODULE <ScopeTag>Proposed product</ScopeTag></div><h3>Minimum Inhibitory Concentration</h3><p>The lowest concentration of an antimicrobial that prevents visible microbial growth under defined test conditions.</p><div className="mic-wells">{["0.25","0.5","1","2","4","8"].map((x,i) => <div key={x} className={i < 3 ? "growth" : "clear"}><i /><b>{x}</b><small>{i < 3 ? "Growth" : "No growth"}</small></div>)}</div><div className="mic-output">SIMULATED OUTPUT <b>MIC = 2 µg/mL</b></div></article><article className="glass-card voc-card"><div className="card-head"><Radio /> AI NOSE / METABOLIC SENSING <ScopeTag>Future R&D</ScopeTag></div><p>Microbial metabolism can produce volatile organic compounds (VOCs). AMR-Eye explores VOC response as an auxiliary metabolic fingerprint—not as a standalone species identifier.</p><MiniChart /><Flow compact items={["Vision", "VOC", "Growth kinetics", "Environment", "Sensor fusion"]} /></article><article className="glass-card lidar-card"><div className="card-head"><Box /> LiDAR / DEPTH <ScopeTag>Future R&D</ScopeTag></div><div className="depth-viz"><span /><span /><span /><span /><span /></div><p>Experimental morphology channel for coarse depth/topography sensing, plate positioning, object detection and morphology research.</p><b>Not an independent bacterial identification method.</b></article><article className="glass-card nephelo-card"><div className="card-head"><Gauge /> NEPHELOMETER <ScopeTag>Proposed product</ScopeTag></div><div className="mc-gauge"><span style={{width:"72%"}} /><i>0.5 McFarland target</i></div><p>Standardized inoculum density matters because improper bacterial concentration can alter zone measurements.</p><blockquote>“We do not want AI to precisely measure a poorly standardized experiment.”</blockquote></article></div></section>

    <section className="section twin-section"><SectionTitle eyebrow="06 · PIMS" title="A digital twin for every plate." copy="Plate Information Management System — one traceable record from inoculation to verification." scope="Proposed product" /><div className="twin-grid"><article className="plate-record"><div className="record-head"><div><small>PLATE ID</small><b>PLT-26-0901-017</b></div><div className="qr" aria-label="Decorative mock QR code">{Array.from({length:36}).map((_,i)=><i key={i} className={i%3===0||i%7===0?"on":""}/>)}</div></div><div className="record-fields">{[["Sample ID","SAM-2409-82"],["Media","Mueller–Hinton agar"],["Organism","E. coli · demo"],["Antibiotics","AMP · CIP · GEN · CTX"],["Inoculation","09:02 IST"],["Temperature","37.0 °C"],["Images","12 frames"],["AI confidence","97.6% mean"],["Standards","Demo EUCAST/CLSI"],["Human review","Pending"],["Report","Draft"]].map(([k,v])=><span key={k}><small>{k}</small><b>{v}</b></span>)}</div></article><article className="plate-timeline"><div className="card-head"><Activity /> GROWTH TIMELINE</div>{[["00:00","Plate registered","Baseline captured"],["02:00","Early lawn","No measurable zones"],["08:00","Zone emergence","Confidence 72%"],["16:00","Stable boundaries","Confidence 94%"],["18:00","Endpoint ready","Human review queued"]].map(([t,a,b],i)=><div key={t} className={i===4?"current":""}><span>{t}</span><i /><p><b>{a}</b><small>{b}</small></p></div>)}</article></div></section>

    <section className="section bahu-section" id="bahu"><SectionTitle eyebrow="07 · SaaS–BAHU" title="The laboratory’s unified human control layer." copy="BAHU — Bio-Automation & Human User Interface — connects people, AI, instruments and biological workflows without hiding professional responsibility." scope="Future R&D" /><div className="bahu-map"><div className="bahu-node human"><UserCheck /><b>HUMAN</b><small>Operator</small></div><ChevronRight /><div className="bahu-core"><span>BAHU</span><b>CONTROL LAYER</b><i className="pulse-ring" /></div><ChevronRight /><div className="bahu-stack"><span><BrainCircuit />AI / Orchestration</span><span><Microscope />Instruments + Sensors</span><span><Bot />Automation</span></div><ChevronRight /><div className="bahu-end"><FlaskConical /><b>BIOLOGICAL WORKFLOW</b><small>Data → verified result</small></div></div><p className="bahu-line"><span>Before</span> Human → individual machine <i /> <span>With AMR-Eye</span> Human → BAHU → orchestrated laboratory</p></section>

    <section className="section console-section"><SectionTitle eyebrow="08 · LAB CONTROL CONSOLE" title="A credible operating surface—not a static mockup." copy="Adjust the simulated controls to explore the proposed operator experience." scope="Prototype demo" /><LabConsole /></section>

    <section className="section architecture-section" id="architecture"><SectionTitle eyebrow="09 · SOFTWARE ARCHITECTURE" title="Quad-Core Nervous System" copy="Control, human interface, local intelligence and cloud coordination remain separable by design." scope="Proposed product" /><div className="quad-architecture">{[
      ["01","THE REFLEX","Firmware / Real-Time Control","STM32 / RTOS",["Temperature","Lighting","Interlocks","Sensors","Timing-critical hardware"],"Zap"],
      ["02","THE INTERFACE","Human / UI Layer","Raspberry Pi",["BAHU","Touchscreen","Sample management","Workflow control","Local UI"],"User"],
      ["03","THE CORTEX","Edge AI","NVIDIA Jetson",["Plate + disc detection","Zone segmentation","Growth tracking","Sensor fusion","Confidence scoring"],"Brain"],
      ["04","THE HIVE","Cloud Intelligence","Connected services",["Multi-device analytics","Model updates","Enterprise dashboard","Remote monitoring","Fleet management"],"Cloud"]
    ].map(([n,name,sub,hw,list,icon]) => <article key={name as string}><div className="layer-index">{n as string}</div><div>{icon==="Zap"?<Zap/>:icon==="User"?<UserCheck/>:icon==="Brain"?<BrainCircuit/>:<Cloud/>}<small>LAYER {n as string}</small><h3>{name as string}</h3><p>{sub as string}</p><b>{hw as string}</b><ul>{(list as string[]).map(x=><li key={x}>{x}</li>)}</ul></div></article>)}</div><div className="architecture-caption"><Flow items={["Reflex · Control", "Interface · Human", "Cortex · AI", "Hive · Cloud"]} /></div><div className="edge-banner"><div><WifiOff /><span><small>EDGE AI</small><b>Camera → Local AI → Local result</b></span></div><p>Lower latency · Offline operation · Privacy · Reduced cloud dependence</p><div>Optional <ChevronRight /> <Cloud /> Cloud sync when connected</div></div></section>

    <section className="section integration-section"><SectionTitle eyebrow="10 · CONNECTED LAB" title="Designed to integrate—not become another silo." scope="Future R&D" /><div className="integration-flow"><div><img src="/amr-eye-icon.png" alt="" /><b>AMR-EYE</b></div><ChevronRight/><div><Database/><b>LIMS / LIS</b><small>Lab systems</small></div><ChevronRight/><div><Server/><b>HIS</b><small>Hospital system</small></div><ChevronRight/><div><HeartPulse/><b>CLINICIAN / ENTERPRISE</b><small>Verified information</small></div></div><p className="integration-note"><b>LIMS</b> Laboratory Information Management System · <b>LIS</b> Laboratory Information System · <b>HIS</b> Hospital Information System</p></section>

    <section className="section automation-section"><SectionTitle eyebrow="11 · CUSTOM LAB AUTOMATION" title="Adapt the platform to the laboratory." copy="AMR-Eye adapts to the laboratory rather than forcing the laboratory to adapt to AMR-Eye." scope="Future R&D" /><Flow items={["Lab audit","SOP mapping","Instrument mapping","Automation design","Hardware modules","Software config","AI config","BAHU deployment"]} /><div className="lab-types">{[["Small diagnostic lab","AST + imaging + smart incubation"],["Hospital laboratory","AST + MIC + LIS + QC + reporting"],["Research laboratory","Time-lapse + multimodal imaging + custom AI"],["Pharmaceutical QC","Environment monitoring + colony analysis + audit trail"]].map(([a,b])=><article key={a}><FlaskConical/><h3>{a}</h3><p>{b}</p></article>)}</div></section>

    <section className="section applications-section" id="applications"><SectionTitle eyebrow="12 · ONE HEALTH" title="One platform architecture. Multiple biological contexts." copy="Potential expansion aligned with a One Health approach; each use case requires its own validation pathway." scope="Future R&D" /><div className="one-health-orbit"><div className="health-core"><img src="/amr-eye-icon.png" alt=""/><b>ONE HEALTH</b></div>{["Human Health","Animal Health","Food / Dairy","Water / Environment","Pharmaceutical QC"].map((x,i)=><span key={x} style={{"--i":i} as CSSProperties}>{x}</span>)}</div></section>

    <section className="section network-section"><SectionTitle eyebrow="13 · AMR INTELLIGENCE NETWORK" title="From validated plates to governed intelligence." copy="Future AMR surveillance architecture — concept demonstration." scope="Future R&D" /><div className="network-dashboard"><div className="india-map" aria-label="Stylized concept map of India"><div className="india-silhouette">INDIA<span className="map-point p1"/><span className="map-point p2"/><span className="map-point p3"/><span className="map-point p4"/><span className="map-point p5"/></div><div className="map-legend"><span><i className="low"/>Lower</span><span><i className="medium"/>Moderate</span><span><i className="high"/>Higher demo signal</span></div></div><div className="network-metrics">{[["Organism","E. coli · demo"],["Antibiotic","Ciprofloxacin"],["Region","West India"],["Resistance %","Synthetic 34%"],["Time trend","↑ 3.2% / demo year"]].map(([k,v])=><div key={k}><small>{k}</small><b>{v}</b></div>)}<MiniChart/><p>Anonymized validated AMR data could support regional trend analysis after governance, consent, quality controls and validation. AMR-Eye does not currently operate a surveillance network.</p></div></div></section>

    <section className="section business-section" id="business"><SectionTitle eyebrow="14 · BUSINESS" title="Hardware opens the door. Recurring services compound value." copy="A system business—not a one-time device sale." /><div className="revenue-stack">{["Hardware / System Installation","Software Subscription","AI-as-a-Service","Automation-as-a-Service","Integration-as-a-Service","AMC / Calibration / Support","Enterprise SaaS"].map((x,i)=><div key={x}><span>0{i+1}</span><b>{x}</b>{i>0&&<small>RECURRING</small>}</div>)}</div></section>

    <section className="section positioning-section"><SectionTitle eyebrow="15 · COMPETITIVE POSITIONING" title="Established systems validate the category." copy="AMR-Eye’s intended position is a staged, resource-conscious platform—not an unproven claim of superiority." /><div className="comparison-table-wrap"><Table><TableHeader><TableRow><TableHead>MARKET CATEGORY</TableHead><TableHead>VALIDATES</TableHead><TableHead>AMR-EYE INTENDED POSITION</TableHead></TableRow></TableHeader><TableBody>{[["Traditional manual AST","Accessible disk diffusion","Digitized measurement + traceability"],["Reshape Biotech","AI imaging + incubation","AMR-first, modular, edge-capable pathway"],["bioMérieux / VITEK","Integrated clinical ID/AST","Start with disk diffusion; build validation discipline"],["BD Phoenix","Automated ID/AST + expert rules","Resource-conscious staged architecture"],["WASPLab / Colibri","Microbiology automation","Future BAHU orchestration + modular automation"]].map(r=><TableRow key={r[0]}>{r.map(c=><TableCell key={c}>{c}</TableCell>)}</TableRow>)}</TableBody></Table></div></section>

    <section className="section roadmap-section" id="roadmap"><SectionTitle eyebrow="16 · PRODUCT ROADMAP" title="Build evidence before breadth." copy="All product tiers below are roadmap concepts unless explicitly marked as the current demo." /><div className="tiers">{[["LITE","Portable imaging + ZOI analysis","Prototype direction"],["CORE","Smart incubation + automated imaging + AST","Proposed"],["PRO","Multimodal sensing + advanced analytics + integration","Future"],["CLINICAL","Validated AST / MIC / QC / standards / traceability","Future · regulated"],["AUTOMATION","Robotics + laboratory orchestration","Long-term"]].map(([n,d,t],i)=><article key={n} className={i===0?"featured":""}><small>AMR-EYE</small><h3>{n}</h3><p>{d}</p><span>{t}</span></article>)}</div><div className="validation-roadmap">{[["01","Synthetic images","Measurement proof"],["02","Reference plates","Manual agreement"],["03","Pilot lab","Error profile"],["04","Standards DB","Traceable S/I/R"],["05","Clinical protocol","Category agreement"],["06","Regulatory planning","Deployment readiness"]].map(([n,a,b])=><div key={n}><span>{n}</span><b>{a}</b><small>{b}</small></div>)}</div></section>

    <section className="section wall-section"><SectionTitle eyebrow="17 · ADVANCED TECHNOLOGY WALL" title="Explore the full vocabulary—without confusing the MVP." copy="Tap any module for a judge-safe explanation." /><div className="tech-wall">{Object.keys(techWall).map(x=><button key={x} onClick={()=>setSelectedTech(x)}>{x}<ChevronRight/></button>)}</div></section>
    <section className="section about-section" id="about"><div className="about-mark"><img src="/amr-eye-icon.png" alt="AMR-Eye app icon" /></div><div><SectionTitle eyebrow="18 · ABOUT AMR-EYE.AI" title="Start with AST. Build the laboratory operating layer." copy="AMR-Eye.AI is an AI-assisted antimicrobial susceptibility testing and bio-automation project led by Namdev Shirodkar. The immediate objective is to convert a defensible computer-vision principle into a validated prototype, dataset and pilot workflow." /><div className="ask-strip"><span>THE NEXT MILESTONE</span><b>Prototype → Dataset → Validation → Pilot Lab → Scale</b></div>{installPrompt && <button className="secondary-action install-action" onClick={install}><Zap/> Install AMR-Eye App</button>}</div></section>

    <footer><div className="footer-brand"><img src="/amr-eye-icon.png" alt=""/><b>AMR-EYE.AI</b><span>AI-Powered AST & Bio-Automation</span></div><p>AMR-Eye.AI is currently an R&D/prototype-stage platform. Demonstrated analyses and values are simulated or experimental and are not intended for clinical diagnosis or treatment decisions. Clinical deployment would require appropriate analytical, clinical and regulatory validation.</p><span>Research / Prototype Demonstration — Not for Clinical Use</span></footer>

    {pitchMode && <div className="pitch-overlay"><div className="pitch-header"><a className="brand" href="#"><img src="/amr-eye-icon.png" alt=""/><span><b>AMR-EYE</b><i>.AI</i></span></a><div><span className="pitch-live"><i className="live-dot"/> PITCH MODE</span><button onClick={()=>setPitchMode(false)}><X/> Exit</button></div></div><div className="pitch-intro"><div><small>JUDGE DEMONSTRATION · LOCAL / DETERMINISTIC</small><h2>From Petri Dish to Digital Intelligence.</h2></div><p>Research / Prototype Demonstration — Not for Clinical Use</p></div><AnalysisDemo pitch onArchitecture={()=>setShowArchitecture(true)} /></div>}
    <Dialog open={!!selectedTech} onOpenChange={(open)=>!open&&setSelectedTech(null)}><DialogContent className="tech-dialog"><DialogHeader><DialogTitle>{selectedTech}</DialogTitle></DialogHeader><ScopeTag>{["NIR","VOC","LiDAR","Sensor Fusion","Robotics","AMR Heatmap","Custom Automation","RAST"].includes(selectedTech||"")?"Future R&D":"Proposed product"}</ScopeTag><p>{selectedTech ? techWall[selectedTech] : ""}</p><small>Capability status is shown conservatively. Clinical use would require dedicated validation.</small></DialogContent></Dialog>
    <Dialog open={showArchitecture} onOpenChange={setShowArchitecture}><DialogContent className="architecture-dialog"><DialogHeader><DialogTitle>AMR-Eye Platform Architecture</DialogTitle></DialogHeader><Flow items={["Human","BAHU","Edge AI","Instruments + Sensors","Verified Result"]}/><p>AST is the first use case. The long-term platform connects humans, AI, controlled hardware, data and biological workflows through one orchestration layer.</p><a href="#architecture" onClick={()=>{setShowArchitecture(false);setPitchMode(false)}} className="primary-action">Open Full Architecture <ChevronRight/></a></DialogContent></Dialog>
  </main>;
}
