"use client";

import { useMemo, useState } from "react";
import { ArrowUpRight, Bot, BrainCircuit, Building2, Cloud, Database, Globe2, GraduationCap, Layers3, Map, Network, RefreshCw, Server, ShieldCheck, Wrench } from "lucide-react";
import { Dialog, DialogContent, DialogHeader, DialogTitle } from "@/components/ui/dialog";


type Status = "Prototype demo" | "Proposed product" | "Future R&D";
type Product = {
  id: string; name: string; label: string; summary: string; status: Status;
  group: "Products" | "Platform" | "Intelligence" | "Services";
  icon: typeof Layers3; points: string[]; action: string; href?: string;
};

const products: Product[] = [
  {id:"apex",name:"APEX XR",label:"FLAGSHIP RESEARCH",summary:"The proposed clinical, research and bio-automation reference platform, bringing the deepest AMR-Eye architecture into one modular workstation.",status:"Proposed product",group:"Products",icon:Layers3,points:["22 proposed subsystems","Direct broth microdilution pathway","Research imaging and constrained automation"],action:"Open flagship knowledge",href:"#apex"},
  { id:"lite", name:"AMR-Eye Lite", label:"PORTABLE AST", summary:"A compact imaging and zone-measurement pathway for resource-conscious labs.", status:"Prototype demo", group:"Products", icon:Layers3, points:["Guided image capture","Synthetic zone-analysis demo","Human review record"], action:"Open analysis", href:"#demo" },
  { id:"core", name:"AMR-Eye Core", label:"CONNECTED WORKBENCH", summary:"Smart incubation, repeat imaging and traceable AST workflow in one proposed system.", status:"Proposed product", group:"Products", icon:Server, points:["Time-lapse acquisition","Plate digital twin","Edge-first operation"], action:"Explore hardware", href:"#hardware" },
  { id:"pro", name:"AMR-Eye Pro", label:"MULTIMODAL LAB", summary:"A future research tier for richer sensing, analytics and laboratory integration.", status:"Future R&D", group:"Products", icon:BrainCircuit, points:["Multiple optical modes","Auxiliary sensor fusion","Custom model workflows"], action:"View product brief" },
  { id:"clinical", name:"Clinical Pathway", label:"VALIDATION TRACK", summary:"A future regulated pathway for validated AST, MIC, QC and standards traceability.", status:"Future R&D", group:"Products", icon:ShieldCheck, points:["Analytical validation","Clinical protocols","Regulatory planning"], action:"View validation path", href:"#roadmap" },
  { id:"bahu", name:"SaaS–BAHU", label:"HUMAN CONTROL LAYER", summary:"A proposed software layer connecting people, instruments, AI and biological workflows.", status:"Future R&D", group:"Platform", icon:Bot, points:["Operator workflow","Instrument orchestration","Human-in-the-loop release"], action:"Open BAHU", href:"#bahu" },
  { id:"edge", name:"Edge AI", label:"LOCAL INTELLIGENCE", summary:"Local processing for lower latency, offline continuity and reduced cloud dependence.", status:"Proposed product", group:"Platform", icon:BrainCircuit, points:["On-device inference","Local result queue","Selective cloud sync"], action:"Open architecture", href:"#architecture" },
  { id:"cloud", name:"AMR-Eye Cloud", label:"FLEET + DATA LAYER", summary:"A proposed connected-services layer for device management, governed data and updates.", status:"Proposed product", group:"Platform", icon:Cloud, points:["Fleet observability","Versioned model delivery","Enterprise workspace"], action:"View platform brief" },
  { id:"connect", name:"Connect", label:"LAB INTEROPERABILITY", summary:"A future connectivity layer for LIMS, LIS, HIS and governed exchange standards.", status:"Future R&D", group:"Platform", icon:Network, points:["LIMS / LIS / HIS","FHIR-ready pathway","Auditable data exchange"], action:"View connectivity", href:"#architecture" },
  { id:"nap", name:"NAP-AMR Command Map", label:"NATIONAL INTELLIGENCE", summary:"A concept for governed AMR signals, hotspots and variation trends across regions.", status:"Future R&D", group:"Intelligence", icon:Map, points:["Synthetic hotspot explorer","Region and organism filters","Policy-ready trend views"], action:"Open intelligence concept", href:"#network" },
  { id:"global", name:"Global AMR Network", label:"LOCAL → GLOBAL", summary:"A federated concept connecting local health centres to national and international views.", status:"Future R&D", group:"Intelligence", icon:Globe2, points:["Local health-centre nodes","Country-specific governance","Cross-border aggregate views"], action:"View network model" },
  { id:"models", name:"Model Registry", label:"MULTIMODAL AI", summary:"Separate models for plate imaging, growth kinetics and research data, each with its own evidence boundary.", status:"Future R&D", group:"Intelligence", icon:Database, points:["Image-to-measurement","Growth-curve analysis","Omics association only with qualified source data"], action:"Explore model stack" },
  { id:"research", name:"Research Studio", label:"COLLEGE + R&D", summary:"A future workspace for universities and research centres to study governed, de-identified datasets.", status:"Future R&D", group:"Intelligence", icon:GraduationCap, points:["Cohort workspaces","Model comparison","Reproducible export"], action:"View research pathway" },
  { id:"government", name:"Government Programs", label:"PUBLIC HEALTH", summary:"A proposed deployment and support pathway for national and state AMR programs.", status:"Future R&D", group:"Services", icon:Building2, points:["Program configuration","Governed aggregation","Training and adoption"], action:"View program model" },
  { id:"support", name:"Maintenance + Support", label:"SYSTEM CARE", summary:"Planned service coverage for devices, software, databases and connected operations.", status:"Proposed product", group:"Services", icon:Wrench, points:["Preventive maintenance","Calibration pathway","Support desk"], action:"View service scope" },
  { id:"updates", name:"Updates + Assurance", label:"CONTINUOUS SERVICE", summary:"Versioned software, model and standards updates with traceability and rollback controls.", status:"Proposed product", group:"Services", icon:RefreshCw, points:["Signed releases","Model registry","Standards database versions"], action:"View update model" },
];

const groups = ["Products", "Platform", "Intelligence", "Services", "All"] as const;
const art:Record<string,string>={lite:"lite",core:"core-reference",pro:"gantry",apex:"pro",clinical:"imaging",bahu:"bahu",edge:"edge",cloud:"cloud",connect:"connect",nap:"network",global:"global",models:"models",research:"research",government:"government",support:"support",updates:"deployment"};
const workflows:Record<string,[string,string,string]> = {
 lite:["Small laboratories and teaching benches","Prepare the plate using the chosen method → controlled image capture → zone measurement → qualified review.","A first imaging pathway. A synthetic interface is available; a validated clinical instrument is not yet established."],
 core:["Laboratories needing repeat imaging and sample traceability","Barcode a plate → controlled incubation → scheduled images → review the digital record.","Adds continuity around plate-based work. Loaded chamber performance, optics and method agreement require validation."],
 pro:["Research laboratories with assay-specific imaging needs","Configure the assay → acquire optical and auxiliary signals → compare time-resolved observations.","Research sensing is assay-specific. VOC fingerprints cannot independently identify species; coarse proximity is not colony profilometry."],
 apex:["Institutions exploring a configurable flagship workstation","Select modules → calibrate the instrument → run a controlled plate or broth workflow → retain a traceable record.","A maximum-configuration architecture proposal. Integration, clinical validation, production design and final pricing remain future work."],
 clinical:["Clinical laboratories preparing a formal validation pathway","Define intended use → qualify the method → validate performance → document quality controls → seek applicable approvals.","No clinical accuracy, regulatory clearance or universal turnaround is claimed. Direct MIC uses broth microdilution."],
 bahu:["Operators coordinating several instruments and workflows","Define a constrained workflow → authorise the run → monitor instrument status → review exceptions and release.","System/Software as a Service with Bio-Automation & Human User Interface. Human responsibility remains explicit."],
 edge:["Sites that need processing close to the instrument","Capture locally → run a qualified model → queue records → sync approved data when connected.","The device architecture proposes local inference. The website itself runs a deterministic demo, not a deployed diagnostic model."],
 cloud:["Multi-site laboratories and institutions","Register a device → manage access → synchronise governed records → review fleet status and versions.","Optional cloud services are proposed. Hosting location, data retention and institutional agreements need to be established."],
 connect:["Laboratories linking instrument records to existing systems","Map identifiers and fields → validate an adapter → exchange records → reconcile acknowledgements.","LIMS, LIS, HIS and FHIR pathways require partner-specific integration, consent and testing. No live connector is operating here."],
 nap:["Government researchers and AMR surveillance programs","Quality-check local records → de-identify → aggregate by region and time → review trends.","A NAP-AMR-aligned concept, not a current government contract or operational surveillance network."],
 global:["National programs and international research collaborations","Keep local governance → agree comparable definitions → share approved aggregates → compare trends.","Country-specific rules, laboratory quality and compatible reporting definitions come before cross-border expansion."],
 models:["Teams evaluating imaging and multimodal research models","Define an input → train and evaluate → version a model → monitor limits and retain a review trail.","Images support visible-feature measurement. Strain, proteins and genomic associations require qualified assays or omics inputs."],
 research:["Colleges, universities and research centres","Select a study → define a protocol → capture time-series data → compare cohorts → retain methods and provenance.","Research tools are proposed. Every assay and dataset needs its own reproducibility, consent and validation checks."],
 government:["State, national and public-sector implementation teams","Scope a program → assess facilities → procure through the applicable route → train teams → monitor adoption.","A proposed selling and deployment model. No procurement approval, tender win or government partnership is implied."],
 support:["Laboratories planning the full system lifecycle","Schedule maintenance → check calibration → record faults → service and requalify the device.","Planned preventive maintenance, database support, training and service documentation. Commercial terms are not final."],
 updates:["Teams responsible for controlled software and database change","Review a release → verify signatures → validate compatibility → deploy with rollback and audit records.","Software, models and standards need separately versioned releases. A language model must never invent clinical breakpoints."]
};

const detailRoutes:Record<string,string>={"edge":"/?topic=topic-45#apex","cloud":"#architecture","connect":"#integration","nap":"#network","global":"#network","models":"/?topic=research-models#apex","research":"#research","government":"#business","support":"/?topic=research-offline#apex","updates":"/?topic=research-offline#apex"};
const detailHref=(p:Product)=>detailRoutes[p.id]||p.href||"#apex";
export default function ProductShowcase() {
 const [group,setGroup]=useState<(typeof groups)[number]>("Products");
 const [query,setQuery]=useState(""); const [selected,setSelected]=useState<Product|null>(null);
 const [compare,setCompare]=useState<string[]>([]);const [comparing,setComparing]=useState(false);
 const visible=useMemo(()=>products.filter(p=>(group==="All"||p.group===group)&&(p.name+" "+p.summary+" "+p.points.join(" ")).toLowerCase().includes(query.toLowerCase())),[group,query]);
 return <section className="section products-section collection" id="products">
  <div className="collection-heading"><span className="eyebrow">02 / EXPLORE THE ECOSYSTEM</span><h2>Built around the work.<br/><em>Designed to connect.</em></h2><p>A family of proposed instruments, software and services. Start with the use case; add complexity only where it earns its place.</p><small>Working names and configurations · Not a final product catalogue</small></div>
  <div className="collection-controls"><div className="product-filters" role="group" aria-label="Product categories">{groups.map(g=><button key={g} aria-pressed={g===group} onClick={()=>setGroup(g)}>{g==="Products"?"Instruments":g}</button>)}</div><label className="collection-search"><span>Find a product</span><input value={query} onChange={e=>setQuery(e.target.value)} type="search" placeholder="Search the collection…"/></label></div>
  <div className="collection-grid">{visible.map(p=><article className="collection-card" key={p.id}><button className="product-open" onClick={()=>setSelected(p)} aria-label={"Explore "+p.name}><div className="collection-art"><img src={"/visuals/"+art[p.id]+".webp"} width="1536" height="1024" loading="lazy" alt={p.name+"  ·  generated concept illustration"}/><span>CONCEPT</span></div><div className="collection-card-copy"><small>{p.label}</small><h3>{p.name}</h3><p>{p.summary}</p><span className="collection-status">{p.status}<ArrowUpRight size={18}/></span></div></button><label className="compare-toggle"><input type="checkbox" checked={compare.includes(p.id)} disabled={!compare.includes(p.id)&&compare.length>=3} onChange={()=>setCompare(old=>old.includes(p.id)?old.filter(id=>id!==p.id):[...old,p.id])}/>Compare</label></article>)}</div>
  {!visible.length&&<p role="status">No matching products. <button className="text-link" onClick={()=>{setQuery("");setGroup("All")}}>Clear filters</button></p>}
  <div className="collection-foot"><p>{visible.length} of {products.length} concepts · Choose up to 3 to compare.</p><button className="solid-link" disabled={compare.length<2} onClick={()=>setComparing(true)}>Compare selected ({compare.length})<ArrowUpRight size={17}/></button><a className="text-link" href="#pathways">Find your use case<ArrowUpRight size={17}/></a></div>
  <div className="evidence-boundary"><ShieldCheck/><p>These are development pathways. Product images illustrate proposed form and function; clinical performance and final configurations require validation.</p></div>
  <Dialog open={!!selected} onOpenChange={open=>!open&&setSelected(null)}><DialogContent className="product-dialog collection-dialog" aria-describedby={undefined}><DialogHeader><span className="eyebrow">{selected?.group} · {selected?.status}</span><DialogTitle>{selected?.name}</DialogTitle></DialogHeader>{selected&&<><p>{selected.summary}</p><h3>Who it is for</h3><p>{workflows[selected.id][0]}</p><h3>The proposed workflow</h3><p>{workflows[selected.id][1]}</p><ul>{selected.points.map(p=><li key={p}>{p}</li>)}</ul><h3>What still needs evidence</h3><p>{workflows[selected.id][2]}</p><div className="atelier-actions"><a className="solid-link" href={detailHref(selected)} onClick={()=>setSelected(null)}>{detailRoutes[selected.id]?"Explore this pathway":selected.href?selected.action:"Explore technical knowledge"}<ArrowUpRight size={17}/></a><a className="text-link" href="#about" onClick={()=>setSelected(null)}>Discuss this pathway<ArrowUpRight size={17}/></a></div><small>Generated concept imagery · Working names and tiers may change.</small></>}</DialogContent></Dialog>
  <Dialog open={comparing} onOpenChange={setComparing}><DialogContent className="comparison-dialog" aria-describedby={undefined}><DialogHeader><DialogTitle>Compare pathways</DialogTitle></DialogHeader><div className="compare-grid">{products.filter(p=>compare.includes(p.id)).map(p=><article key={p.id}><h3>{p.name}</h3><small>{p.status}</small><h4>Best-fit use case</h4><p>{workflows[p.id][0]}</p><ul>{p.points.map(t=><li key={t}>{t}</li>)}</ul><a className="text-link" href={detailHref(p)} onClick={()=>setComparing(false)}>Go deeper<ArrowUpRight size={17}/></a></article>)}</div><p>Comparisons describe proposed scope, not validated product specifications or final prices.</p></DialogContent></Dialog>
 </section>;
}
