"use client";
import {useState,useMemo,useEffect} from "react";
import {ArrowUpRight,ArrowRight,Mail,Search,Check,Copy,ShieldCheck} from "lucide-react";
import type dossier from "./dossier.json";

const audiences=[
 {name:"Investors & judges",title:"Understand the opportunity.",text:"Start with the problem and the first measurable workflow. Then examine a modular business model, recognition and the gates between a prototype and a deployable product.",image:"flagship",links:[["Business & service model","business"],["Wins & recognition","recognition"],["Evidence roadmap","roadmap"]]},
 {name:"Laboratories",title:"Start with your workflow.",text:"Explore how calibrated imaging and human review could support plate-based work. Compare the portable, connected and flagship pathways, then inspect sample traceability and integration requirements.",image:"imaging",links:[["Try a synthetic AST review","demo"],["Compare product pathways","products"],["LIMS / LIS connectivity","integration"]]},
 {name:"Colleges & researchers",title:"Follow a question deeper.",text:"Explore 20 proposed use cases, assay-specific research modules and the original source register. Study how optical measurement, incubation and structured records could support reproducible experiments.",image:"pro",links:[["Open the research library","apex"],["Explore imaging modes","imaging"],["Meet the team","team"]]},
 {name:"Government & public health",title:"Connect evidence to preparedness.",text:"Examine a future path from quality-controlled laboratory records to governed regional intelligence. Explore deployment, training and support alongside country-specific privacy and reporting requirements.",image:"network",links:[["AMR network concept","network"],["Public-health products","products"],["One Health applications","applications"]]},
 {name:"Everyone",title:"Begin with one plate.",text:"Antimicrobial resistance means microbes can resist medicines intended to treat them. AMR-Eye explores ways to digitize laboratory observations, keep qualified people in control and make reliable information easier to connect.",image:"imaging",links:[["The problem & proposed workflow","problem"],["Try the demonstration","demo"],["Browse the whole project","apex"]]}
];
export function Pathways(){const [selected,setSelected]=useState(0);const item=audiences[selected];return <section id="pathways" className="section editorial-page"><span className="eyebrow">01 / DISCOVER</span><h2>Different perspectives.<br/><em>One connected idea.</em></h2><div className="audience-tabs" role="group" aria-label="Choose your perspective">{audiences.map((a,i)=><button key={a.name} aria-pressed={selected===i} onClick={()=>setSelected(i)}>{a.name}</button>)}</div><div className="audience-detail" key={item.name}><div><small>{item.name}</small><h3>{item.title}</h3><p>{item.text}</p><nav>{item.links.map(([label,id])=><a href={`#${id}`} key={id}>{label}<ArrowUpRight size={18}/></a>)}</nav></div><figure><img src={`/visuals/${item.image}.webp`} alt="Generated AMR-Eye concept illustration" width="1536" height="1024"/><figcaption>Proposed design / illustrative concept</figcaption></figure></div><a className="text-link" href="#guide">Need help finding a topic? Open the project guide<ArrowRight size={18}/></a></section>}

export function Recognition(){return <section className="section editorial-page" id="recognition"><span className="eyebrow">THE PROJECT IN THE WORLD</span><h2>Ideas presented.<br/><em>Progress recognised.</em></h2><p className="editorial-intro">AMR-Eye’s innovation and pitching milestones. Recognition celebrates the project; clinical performance still needs its own evidence.</p><div className="recognition-list"><article><div className="recognition-number">02<small>SECOND PLACE</small></div><div><span className="eyebrow">23 JANUARY 2026 · GOA UNIVERSITY</span><h3>Bio-InnoQuest</h3><h4>Harnessing Biodiversity and Bio-innovation · HBB 2026</h4><p>AMR-EYE: An AI-enabled Lab-in-a-Box for Automated AST Interpretation received second place in the innovation competition at Goa University’s three-day national conference.</p><details><summary>Read the project reference</summary><p>The HBB abstract book lists the project as IQ-01 in the Bio-InnoQuest session on 23 January 2026, with Namdev Shirodkar, Tanishq Chari and Trelita de Sousa, St. Xavier’s College, Mapusa. The project’s recognition record documents the second-place award.</p><small>Sources: HBB 2026 official abstract book; project-held Certificate of Appreciation and recognition record.</small></details></div></article><article><div className="recognition-number">GSF<small>IDEA PITCHING</small></div><div><span className="eyebrow">2026 · GOA</span><h3>Goa Startup Festival</h3><h4>AMR-Eye idea-pitching journey</h4><p>The AMR-Eye pitch presents AI-assisted antimicrobial susceptibility testing as the starting point for modular laboratory automation, alongside the staged product and service model.</p><details><summary>Read the project reference</summary><p>The project repository includes the Goa Startup Festival 2026 six-slide idea pitch, followed by a September 2026 Round 2 presentation package. These records establish the pitching journey; no final GSF award or investment is claimed here.</p></details><a className="text-link" href="#business">Explore the business story<ArrowUpRight size={16}/></a></div></article></div><a className="text-link" href="#project-progress">View the development record<ArrowUpRight size={16}/></a></section>}

const team=[
 ["NS","Namdev Tukaram Shirodkar","Project lead · AI & hardware","Co-founder and lead researcher. Connects the microbiology problem, instrument architecture and software direction, and leads the project’s presentation and collaboration work."],
 ["TC","Tanishq Chari","Co-founder · Biology & systems","Lead researcher with a focus on microbiological workflows and system integration. Contributes to the hardware and biological workflow direction."],
 ["MN","Mahima Naik","Software & AI","Contributes to the project’s software and AI narrative, including the relationship between image measurement, standards interpretation and human review."],
 ["HP","Herambh Prabhu Dessai","AMR impact & public health","Contributes to the NAP-AMR and impact perspective, connecting laboratory capability to the wider public-health problem."],
 ["V","Vishwajee","Scenario modelling & public-welfare narrative","Develops pandemic-preparedness scenarios and asks what could change if this infrastructure already existed. Challenges assumptions and explores possible time and resource advantages without unsupported life-saving claims."]
];
export function Team(){return <section id="team" className="section editorial-page"><span className="eyebrow">PEOPLE BEHIND THE PROJECT</span><h2>Biology meets engineering.<br/><em>People make it work.</em></h2><div className="team-list">{team.map(([initials,name,role,bio])=><article key={name}><span className="initials">{initials}</span><div><h3>{name}</h3><strong>{role}</strong><p>{bio}</p></div></article>)}</div><div className="mentor-note"><span className="eyebrow">RESEARCH MENTORSHIP</span><h3>Dr. Trelita de Sousa</h3><p>Research guide and corresponding author in the original AMR-Eye materials at St. Xavier’s College, Mapusa, Goa.</p></div><a className="solid-link" href="#about">Start a conversation<Mail size={18}/></a></section>}

export function Contact(){const [kind,setKind]=useState('Request a demo');const [name,setName]=useState('');const [org,setOrg]=useState('');const [note,setNote]=useState('');const [copied,setCopied]=useState(false);const message=`Hello AMR-Eye team,\n\n${kind}\nName: ${name}\nOrganisation: ${org}\n\n${note}`;return <div className="contact-panel"><div><span className="eyebrow">LET’S TALK</span><h3>Bring your perspective.</h3><p>Explore a demo, discuss a lab workflow or talk about research and investment.</p><a href="mailto:namdevshirodkar20@gmail.com">namdevshirodkar20@gmail.com<ArrowUpRight size={17}/></a><small>This opens your email app. Nothing is sent or stored by this website.</small></div><form onSubmit={e=>{e.preventDefault();location.href=`mailto:namdevshirodkar20@gmail.com?subject=${encodeURIComponent('AMR-Eye · '+kind)}&body=${encodeURIComponent(message)}`}}><label>I’d like to<select value={kind} onChange={e=>setKind(e.target.value)}><option>Request a demo</option><option>Discuss a laboratory pilot</option><option>Explore investment</option><option>Collaborate on research</option><option>Discuss a public-health program</option><option>Contact the team</option></select></label><div className="contact-fields"><label>Name<input value={name} onChange={e=>setName(e.target.value)} autoComplete="name" required/></label><label>Organisation<input value={org} onChange={e=>setOrg(e.target.value)} autoComplete="organization"/></label></div><label>Your message<textarea rows={3} required value={note} onChange={e=>setNote(e.target.value)} placeholder="What would you like to explore?"/></label><div className="atelier-actions"><button className="solid-link" type="submit">Open email draft<Mail size={17}/></button><button className="text-link" type="button" onClick={async()=>{try{await navigator.clipboard.writeText(message);setCopied(true)}catch{setCopied(false)}}}>{copied?<Check size={16}/>:<Copy size={16}/>} {copied?'Draft copied':'Copy draft'}</button></div></form></div>}

export function ProjectGuide(){const [data,setData]=useState<typeof dossier|null>(null);useEffect(()=>{let active=true;import("./dossier.json").then(d=>{if(active)setData(d.default)});return()=>{active=false}},[]);const [query,setQuery]=useState('');const [submitted,setSubmitted]=useState('');const results=useMemo(()=>{const terms=submitted.toLowerCase().match(/[a-z0-9]+/g)?.filter(t=>t.length>2&&!['what','does','the','how','for','and','can','are','with'].includes(t))||[];return (data?.topics||[]).map(t=>({topic:t,score:terms.reduce((n,term)=>n+(t.title.toLowerCase().includes(term)?5:0)+(JSON.stringify(t).toLowerCase().includes(term)?1:0),0)})).filter(x=>x.score>0).sort((a,b)=>b.score-a.score).slice(0,4)},[submitted,data]);return <section className="section editorial-page" id="guide"><span className="eyebrow">PROJECT GUIDE</span><h2>A question is<br/><em>a good place to start.</em></h2><p className="editorial-intro">Find source-linked explanations in the AMR-Eye library. This free guide searches the project record locally; it does not run a generative AI model.</p><form className="guide-search" onSubmit={e=>{e.preventDefault();setSubmitted(query)}}><Search/><input aria-label="Ask the project guide" value={query} onChange={e=>setQuery(e.target.value)} placeholder="How does direct MIC work?" required/><button type="submit" aria-label="Search project knowledge"><ArrowRight/></button></form><div className="guide-prompts">{['What is BAHU?','How does direct MIC work?','What needs validation?','What can edge computing do?'].map(q=><button key={q} onClick={()=>{setQuery(q);setSubmitted(q)}}>{q}</button>)}</div><div className="guide-results" aria-live="polite">{submitted&&<h3>{results.length?`Project references for “${submitted}”`:'No matching references yet'}</h3>}{results.map(({topic:t})=><article key={t.id}><small>{t.category} · {t.status}</small><h3>{t.title}</h3><p>{t.text[0]||t.tables[0]?.[1]?.join(' · ')}</p><a href={`/?topic=${t.id}#apex`}>Read full topic and sources<ArrowUpRight size={17}/></a></article>)}{submitted&&!results.length&&<p>Try a shorter subject such as “MIC”, “incubation” or “validation”, or <a href="#apex">browse all 83 topics</a>.</p>}</div><div className="guide-note"><ShieldCheck size={20}/><p>For image analysis, use the <a href="#demo">labelled synthetic AST demo</a>. For product guidance, choose a <a href="#pathways">visitor perspective</a>. Clinical interpretation always requires qualified review.</p></div></section>}

