"use client";
import {useState,useMemo,useEffect} from "react";
import {ArrowUpRight,ArrowRight,Mail,Search,Check,Copy,ShieldCheck} from "lucide-react";
import dossier from "./dossier.json";
import {questions,searchTopics} from "./search-core.mjs";

const audiences=[
 {name:"Investors & judges",title:"Understand the opportunity.",text:"Start with the problem and the first measurable workflow. Then examine a modular business model, recognition and the gates between a prototype and a deployable product.",image:"flagship",links:[["Business & service model","business"],["Wins & recognition","recognition"],["Evidence roadmap","roadmap"]]},
 {name:"Laboratories",title:"Start with your workflow.",text:"Explore how calibrated imaging and human review could support plate-based work. Compare the portable, connected and flagship pathways, then inspect sample traceability and integration requirements.",image:"imaging",links:[["Try a synthetic AST review","demo"],["Compare product pathways","products"],["LIMS / LIS connectivity","integration"]]},
 {name:"Colleges & researchers",title:"Follow a question deeper.",text:"Explore proposed applications, research questions and their validation needs. Study how optical measurement, incubation and structured records could support reproducible experiments.",image:"pro",links:[["Open the research library","apex"],["Explore imaging modes","imaging"],["Meet the team","team"]]},
 {name:"Government & public health",title:"Connect evidence to preparedness.",text:"Examine a future path from quality-controlled laboratory records to governed regional intelligence. Explore deployment, training and support alongside country-specific privacy and reporting requirements.",image:"network",links:[["AMR network concept","network"],["Public-health products","products"],["One Health applications","applications"]]},
 {name:"Everyone",title:"Begin with one plate.",text:"Antimicrobial resistance means microbes can resist medicines intended to treat them. AMReye.AI explores ways to digitize laboratory observations, keep qualified people in control and make reliable information easier to connect.",image:"imaging",links:[["The problem & proposed workflow","problem"],["Try the demonstration","demo"],["Browse the whole project","apex"]]}
];
export function Pathways(){const [selected,setSelected]=useState(0);useEffect(()=>{const read=()=>{const p=new URLSearchParams(location.search).get('perspective');const n=['investor','laboratory','researcher','public-health','everyone'].indexOf(p||'');setSelected(n<0?0:n)};read();addEventListener('popstate',read);return()=>removeEventListener('popstate',read)},[]);const select=(n:number)=>{setSelected(n);const u=new URL(location.href);u.searchParams.set('perspective',['investor','laboratory','researcher','public-health','everyone'][n]);u.hash='pathways';history.pushState({},'',u)};const item=audiences[selected];return <section id="pathways" className="section editorial-page"><span className="eyebrow">01 / DISCOVER</span><h2>Different perspectives.<br/><em>One connected idea.</em></h2><div className="audience-tabs" role="group" aria-label="Choose your perspective">{audiences.map((a,i)=><button key={a.name} aria-pressed={selected===i} onClick={()=>select(i)}>{a.name}</button>)}</div><div className="audience-detail" key={item.name}><div><small>{item.name}</small><h3>{item.title}</h3><p>{item.text}</p><nav>{item.links.map(([label,id])=><a href={`#${id}`} key={id}>{label}<ArrowUpRight size={18}/></a>)}</nav></div><div className="audience-route-map" aria-hidden="true"><span>01</span><b>Explore the need</b><i/><span>02</span><b>Inspect the workflow</b><i/><span>03</span><b>Read the evidence</b></div></div><a className="text-link" href="#guide">Need help finding a topic? Open the project guide<ArrowRight size={18}/></a></section>}

export function Recognition(){return <section className="section editorial-page" id="recognition"><span className="eyebrow">THE PROJECT IN THE WORLD</span><h2>Ideas presented.<br/><em>Progress recognised.</em></h2><p className="editorial-intro">AMReye.AI’s innovation and pitching milestones. Recognition celebrates the project; clinical performance still needs its own evidence.</p><div className="recognition-list"><article><div className="recognition-number">PU<small>PRE-INCUBATION</small></div><div><span className="eyebrow">3 SEPTEMBER 2026 · PARUL UNIVERSITY, GOA</span><h3>Selected startup · PU EPIC</h3><h4>Pre-Incubation Program | Goa Startup Festival 2026</h4><p>Selected for PU EPIC pre-incubation, a step toward mentoring and project development. This does not establish funding or clinical validation.</p></div></article><article><div className="recognition-number">02<small>SECOND PLACE</small></div><div><span className="eyebrow">23 JANUARY 2026 · GOA UNIVERSITY</span><h3>Bio-InnoQuest</h3><h4>Harnessing Biodiversity and Bio-innovation · HBB 2026</h4><p>AMReye.AI: An AI-enabled Lab-in-a-Box for Automated AST Interpretation received second place in the innovation competition at Goa University’s three-day national conference.</p></div></article><article><div className="recognition-number">GSF<small>IDEA PITCHING</small></div><div><span className="eyebrow">2026 · GOA</span><h3>Goa Startup Festival</h3><h4>AMReye.AI idea-pitching journey</h4><p>The AMReye.AI pitch presents AI-assisted antimicrobial susceptibility testing as the starting point for modular laboratory automation, alongside the staged product and service model.</p><a className="text-link" href="#business">Explore the business story<ArrowUpRight size={16}/></a></div></article></div><a className="text-link" href="#project-progress">View the development record<ArrowUpRight size={16}/></a></section>}

const team=[
 ["NS","Namdev Tukaram Shirodkar","Overall lead · Public health & AMR strategy","Leads the microbiology framework, Goa case study, public-health spending analysis and project coordination. Sets the research direction and connects AMReye.AI to long-term public-health needs."],
 ["TC","Tanishq Chari","Co-founder · Hardware & technical feasibility","Develops the prototype architecture, incubation and imaging workflow, technical requirements and deployment costs. Separates current capabilities from future development."],
 ["MN","Mahima Naik","Research, data & healthcare accessibility","Collects literature and government data, organises evidence tables and studies diagnostic accessibility, public hospitals and patient-side implications."],
 ["HP","Herambh Prabhu Dessai","Policy & implementation","Studies government-health schemes, institutional feasibility and implementation. Develops recommendations for moving from a pilot to district, state and national deployment."],
 ["V","Vishwajee","Scenario modelling & public-welfare narrative","Develops pandemic-preparedness scenarios and asks what could change if this infrastructure already existed. Challenges assumptions and explores possible time and resource advantages without unsupported life-saving claims."]
];
export function Team(){return <section id="team" className="section editorial-page"><span className="eyebrow">PEOPLE BEHIND THE PROJECT</span><h2>Biology meets engineering.<br/><em>People make it work.</em></h2><div className="team-list">{team.map(([initials,name,role,bio])=><article key={name}><span className="initials">{initials}</span><div><h3>{name}</h3><strong>{role}</strong><p>{bio}</p></div></article>)}</div><div className="mentor-note"><span className="eyebrow">RESEARCH MENTORSHIP</span><h3>Dr. Trelita de Sousa</h3><p>Research guide and corresponding author in the original AMReye.AI materials at St. Xavier’s College, Mapusa, Goa.</p></div><a className="solid-link" href="#about">Start a conversation<Mail size={18}/></a></section>}

export function Contact(){const [kind,setKind]=useState('Request a demo');const [name,setName]=useState('');const [org,setOrg]=useState('');const [note,setNote]=useState('');const [copied,setCopied]=useState(false);const [copyError,setCopyError]=useState('');const message=`Hello AMReye.AI team,\n\n${kind}\nName: ${name}\nOrganisation: ${org}\n\n${note}`;return <div className="contact-panel"><div><span className="eyebrow">LET’S TALK</span><h3>Bring your perspective.</h3><p>Explore a demo, discuss a lab workflow or talk about research and investment.</p><a href="mailto:namdevshirodkar20@gmail.com">namdevshirodkar20@gmail.com<ArrowUpRight size={17}/></a><small>This opens your email app. Nothing is sent or stored by this website.</small></div><form onSubmit={e=>{e.preventDefault();location.href=`mailto:namdevshirodkar20@gmail.com?subject=${encodeURIComponent('AMReye.AI · '+kind)}&body=${encodeURIComponent(message)}`}}><label>I’d like to<select value={kind} onChange={e=>setKind(e.target.value)}><option>Request a demo</option><option>Discuss a laboratory pilot</option><option>Explore investment</option><option>Collaborate on research</option><option>Discuss a public-health program</option><option>Contact the team</option></select></label><div className="contact-fields"><label>Name<input value={name} onChange={e=>setName(e.target.value)} autoComplete="name" required/></label><label>Organisation<input value={org} onChange={e=>setOrg(e.target.value)} autoComplete="organization"/></label></div><label>Your message<textarea rows={3} required value={note} onChange={e=>setNote(e.target.value)} placeholder="What would you like to explore?"/></label><div className="atelier-actions"><button className="solid-link" type="submit">Open email draft<Mail size={17}/></button><button className="text-link" type="button" onClick={async()=>{try{await navigator.clipboard.writeText(message);setCopied(true);setCopyError('')}catch{setCopied(false);setCopyError('Copy was unavailable. Select the draft text or open your email app.')}}}>{copied?<Check size={16}/>:<Copy size={16}/>} {copied?'Draft copied':'Copy draft'}</button></div><p role="status">{copyError}</p></form></div>}

export function ProjectGuide(){const [query,setQuery]=useState(''),[submitted,setSubmitted]=useState('');const results=useMemo(()=>searchTopics(dossier.topics,submitted).slice(0,6),[submitted]);return <section id="guide" className="section editorial-page"><span className="eyebrow">PROJECT GUIDE</span><h2>Start with a question.</h2><p>Search the AMReye.AI overview and follow the connected topics.</p><form className="guide-search" onSubmit={e=>{e.preventDefault();setSubmitted(query)}}><Search/><input aria-label="Ask the project guide" value={query} onChange={e=>setQuery(e.target.value)} placeholder="What does a campus audit include?" required/><button aria-label="Search project knowledge"><ArrowRight/></button></form>{[...new Set(questions.map(q=>q[0]))].map(group=><details key={group} open={group==='Start here'}><summary>{group}</summary><div className="guide-prompts">{questions.filter(q=>q[0]===group).map(([,q])=><button key={q} onClick={()=>{setQuery(q);setSubmitted(q)}}>{q}</button>)}</div></details>)}<div className="guide-results" aria-live="polite">{submitted&&<h3>{results.length?`Results for “${submitted}”`:'No matching topics yet'}</h3>}{results.map(({topic:t})=><article key={t.id}><small>{t.category} · {t.status}</small><h3>{t.title}</h3><p>{t.text[0]}</p><a href={'/?topic='+encodeURIComponent(t.id)+'#apex'}>Explore this topic ↗</a></article>)}{submitted&&!results.length&&<p>Try a shorter subject, or <a href="#apex">browse the library</a>.</p>}</div></section>}