"use client";
import {useState} from 'react';
import {ArrowUpRight,BrainCircuit,Camera,Database,FlaskConical,Layers3,LockKeyhole,Ruler,ShieldCheck,Users} from 'lucide-react';
import knowledge from './public-knowledge.json';
type Area='ast'|'imaging'|'ai'|'standards'|'hardware'|'data'|'applications'|'development';
type Step=[string,string,string];
const stories:Record<Area,{title:string;kind:'flow'|'branches';steps:Step[]}>= {
 ast:{title:'From plate to review',kind:'flow',steps:[['Photograph','A controlled plate image starts the proposed reading workflow.','compendium-011-015'],['Measure','Reader V1 focuses on endpoint zone measurements. The website demonstration uses fictional examples.','reader-v1'],['Check','Unreadable images should lead to recapture, not a guessed answer.','research-readability'],['Review','A qualified person reviews the result and its limitations.','topic-44']]},
 imaging:{title:'What makes a measurement useful?',kind:'flow',steps:[['Choose signal','Decide what needs measuring before choosing a sensor.','compendium-035-042'],['Control light','Lighting changes which sample features are visible.','topic-23'],['Capture','A controlled whole-plate camera could make observations comparable.','topic-20'],['Check scale','A pixel distance needs a known scale before it becomes millimetres.','topic-21']]},
 ai:{title:'AI assistance, with boundaries',kind:'flow',steps:[['Find features','Computer vision may locate plates, identifiers, discs and visible boundaries.','compendium-092-102'],['Measure','Measuring an image is different from predicting an early biological result.','compendium-103-112'],['Test model','More inputs do not automatically make a model reliable. Representative testing matters.','compendium-113-122'],['Human decision','A qualified person remains responsible for accepting laboratory results.','compendium-123-132']]},
 standards:{title:'Evidence before clinical claims',kind:'flow',steps:[['Plan study','Choose a suitable comparison method and include difficult cases.','compendium-197-204'],['Check software','Test the rules, interface and failure behaviour.','compendium-205-215'],['Review','Keep human decisions and corrections traceable.','topic-44'],['Pass gates','Safety evidence and acceptance criteria matter more than a polished demo.','compendium-225-228']]},
 hardware:{title:'Inside the proposed architecture',kind:'branches',steps:[['Separate zones','Separate biological work, instruments and computing.','topic-16'],['Conditions','Monitor temperature and humidity before trusting a measurement.','topic-28'],['Safety control','Independent control should handle time-sensitive safety responses.','topic-17'],['Operator','Show the workflow, measurements and warnings clearly.','topic-18']]},
 data:{title:'Keep the evidence connected',kind:'flow',steps:[['Capture','Retain the original observation and its identity.','topic-11'],['Join records','Keep images, measurements and context together.','compendium-133-142'],['Record changes','Preserve original values. Corrections invalidate previous approval.','research-validation-mode'],['Control access','Use permissions, access limits and retention rules.','privacy-governance']]},
 applications:{title:'Different questions. Different evidence.',kind:'branches',steps:[['Clinical testing','Each intended clinical function would need appropriate validation.','topic-48'],['Stewardship','Validated results may support antibiotic use alongside clinical judgement.','topic-55'],['Public health','Governed records could support stewardship, access and public-health research.','compendium-189-196'],['Phenomics','Observable growth and appearance do not by themselves reveal a genome.','topic-58']]},
 development:{title:'Turn a concept into testable work',kind:'flow',steps:[['Show maturity','Keep the proof of concept separate from proposals and future research.','topic-8'],['Assign roles','Make technical, scientific and organisational responsibilities clear.','research-research-roles'],['Reduce risk','Prioritise the experiments and engineering needed to test an idea.','topic-83'],['Prepare service','Plan installation, calibration, repair, training and support.','compendium-259-266']]}
};
const icons={ast:FlaskConical,imaging:Camera,ai:BrainCircuit,standards:ShieldCheck,hardware:Layers3,data:Database,applications:Users,development:Ruler};
export const routeArea:Record<string,Area>={problem:'ast',hardware:'hardware',technology:'ai',imaging:'imaging',modules:'hardware',twin:'data',bahu:'hardware',architecture:'data',integration:'data',automation:'hardware',applications:'applications',positioning:'standards',wall:'development',sources:'standards','project-progress':'development',business:'development',roadmap:'standards',research:'applications',references:'hardware'};

export function ScalePlayground(){const [pixels,setPixels]=useState(160),[known,setKnown]=useState(true);return <div className="scale-playground"><div className="scale-lab-heading"><Ruler/><b>Try a measurement</b><span>Synthetic scale example</span></div><div className="scale-ruler" aria-hidden="true"><div style={{width:`${pixels/240*100}%`}}><i/><span>{pixels} pixels</span><i/></div></div><label>Distance in the image<input type="range" min="40" max="240" step="10" value={pixels} onChange={e=>setPixels(Number(e.target.value))} aria-label="Example pixel distance"/></label><label className="scale-known"><input type="checkbox" checked={known} onChange={e=>setKnown(e.target.checked)}/>Known scale: 10 pixels per millimetre</label><output aria-live="polite">{known?<><b>{(pixels/10).toFixed(1)} mm</b><span>{pixels} pixels ÷ 10 pixels/mm</span></>:<><b>Measurement unavailable</b><span>Without a scale, pixels cannot reliably become millimetres.</span></>}</output></div>}
export default function VisualExplainer({area='ast',onTopic,compact=false}:{area?:string;onTopic?:(id:string)=>void;compact?:boolean}){
 const key=(area in stories?area:'ast') as Area;const story=stories[key];const [choice,setChoice]=useState(0);const selected=story.steps[choice];const Icon=icons[key];const topic=knowledge.topics.find(t=>t.id===selected[2]);
 return <section className={'visual-explainer '+(compact?'visual-explainer-compact':'')} aria-label={story.title} key={key}><div className="visual-explainer-heading"><span className="visual-kicker">Explore visually</span><h2>{story.title}</h2><p>{story.kind==='branches'?'Select a part to see its role. These are connected areas, not sequential steps.':'Select a step to see how it connects.'}</p></div>
 {story.kind==='branches'?<div className="visual-branch-map"><div className="visual-map-center"><Icon/><span>{key==='applications'?'Possible uses':'Proposed system'}</span></div><svg viewBox="0 0 400 200" preserveAspectRatio="none" aria-hidden="true"><path d="M200 100 L65 35 M200 100 L335 35 M200 100 L65 165 M200 100 L335 165"/></svg>{story.steps.map(([title],i)=><button key={title} className={'branch-node node-'+i} aria-pressed={choice===i} onClick={()=>setChoice(i)}><span>0{i+1}</span><b>{title}</b></button>)}</div>:<div className="visual-flow-map">{story.steps.map(([title],i)=><button key={title} aria-pressed={choice===i} onClick={()=>setChoice(i)}><span>{i+1}</span><b>{title}</b></button>)}</div>}
 <div className="visual-explainer-detail" role="status"><Icon/><div><small>{topic?.status}</small><h3>{selected[0]}</h3><p>{selected[1]}</p>{onTopic?<button onClick={()=>onTopic(selected[2])}>Topic and references<ArrowUpRight size={16}/></button>:<a href={'/library?topic='+selected[2]}>Topic and references<ArrowUpRight size={16}/></a>}</div></div>
 {!compact&&key==='imaging'&&<ScalePlayground/>}
 </section>
}
