"use client";
import {useEffect,useState} from 'react';
import {ArrowLeft,ArrowRight,Camera,Check,ChevronRight,Cloud,Database,FlaskConical,GraduationCap,Layers3,LockKeyhole,Microscope,Play,Ruler,ShieldCheck,Users,X} from 'lucide-react';
import {demoDiscs} from './demo-rules.mjs';

const slides=[
 {title:'One plate. A clearer picture.',copy:'Antibiotic tests leave visible zones on a plate. AMReye.AI explores how to measure them and keep a reviewable record.',prompt:'Select a disc. Move the example boundary.',label:'The problem',status:'Synthetic teaching example',link:'Try the full demonstration',target:'demo'},
 {title:'See how a record takes shape.',copy:'A photograph is only the start. Scale, measurement and qualified human review need to stay connected.',prompt:'Choose a step to follow the proposed workflow.',label:'The workflow',status:'Proposed workflow · Synthetic website demo',link:'Explore the workflow',target:'workflow'},
 {title:'Start small. Add useful capability.',copy:'Reader V1 is the early development priority. More complex instrument configurations remain proposals or research.',prompt:'Choose a configuration to see its scope.',label:'The platform',status:'Prototype and proposed product family',link:'Compare the products',target:'products'},
 {title:'Local records. Governed insight.',copy:'The future network would share approved information, not unrestricted laboratory records. Quality and privacy come first.',prompt:'Follow the record through each boundary.',label:'Public health',status:'Future concept · No live data exchange',link:'Try the network explorer',target:'network'},
 {title:'Milestones are not validation.',copy:'The project reports Bio-InnoQuest second place and PU EPIC pre-incubation selection. A clinical product needs a separate evidence journey.',prompt:'Select a gate to see what must be established.',label:'The evidence',status:'Project-reported recognition',link:'Explore the evidence roadmap',target:'roadmap'},
 {title:'Where could you contribute?',copy:'Explore a workflow, help frame a research question or discuss the path from prototype to responsible deployment.',prompt:'Choose your perspective.',label:'Get involved',status:'Collaboration invitation, not a confirmed partnership',link:'Start a conversation',target:'about'}
];
const workflow=[['Capture','A controlled image with a known scale.'],['Measure','Visible zones become measurements with uncertainty.'],['Review','A qualified person checks the boundary and warnings.'],['Record','Keep the original, changes and review together.']];
const configurations=[
 {name:'Reader V1',state:'Early prototype direction',icon:Camera,features:['Endpoint plate image','Zone measurement','Qualified review'],note:'The website has a synthetic demonstration. A validated clinical instrument is not established.'},
 {name:'Core',state:'Proposed product',icon:Layers3,features:['Repeat imaging','Controlled incubation','Connected plate record'],note:'Instrument integration and method agreement still require development and testing.'},
 {name:'APEX XR',state:'Proposed research platform',icon:FlaskConical,features:['Configurable modules','Assay-specific sensing','Constrained automation'],note:'A reference architecture, not a completed multimodal diagnostic system.'}
];
const gates=[['Prototype','Build a repeatable imaging and review workflow.','Current focus'],['Measurement','Compare against a reference method and quantify uncertainty.','Evidence required'],['Supervised pilot','Agree a protocol, responsibilities and suitable partners.','Proposed next step'],['Clinical release','Establish intended-use evidence and applicable approvals.','Not established']];

function PitchPlate(){
 const [disc,setDisc]=useState(0),[mm,setMm]=useState(25.4);
 return <div className="pitch-plate-scene"><svg viewBox="0 0 340 300" role="group" aria-label="Explore a synthetic antibiotic test plate">
  <circle cx="170" cy="145" r="126" fill="#0b3440" stroke="#71b2c0" strokeWidth="2"/>
  <circle cx="170" cy="145" r="117" fill="#123e42" stroke="#235e62"/>
  {demoDiscs.map((d,i)=>{const a=(i*60-90)*Math.PI/180,x=170+75*Math.cos(a),y=145+75*Math.sin(a),r=(i===disc?mm:d.mm)*126/90;return <g key={d.code} tabIndex={0} role="button" aria-label={'Inspect '+d.code} aria-pressed={i===disc} onClick={()=>{setDisc(i);setMm(d.mm)}} onKeyDown={e=>{if(e.key==='Enter'||e.key===' '){e.preventDefault();setDisc(i);setMm(d.mm)}}}><circle cx={x} cy={y} r={Math.max(r,22)} fill="transparent"/><circle cx={x} cy={y} r={r} fill={i===disc?'#00d6e526':'#cceede10'} stroke={i===disc?'#00e4ef':'#78a6a6'} strokeWidth={i===disc?2:1}/><circle cx={x} cy={y} r="9" fill="#e8f0df"/><text x={x} y={y+3} textAnchor="middle" fontSize="8" fill="#102f37">{d.code}</text>{i===disc&&<><line x1={x-r} x2={x+r} y1={y} y2={y} stroke="#f8ffff"/><text x={x} y={y+r+16} textAnchor="middle" fill="#eaffff" fontSize="12">{mm.toFixed(1)} mm</text></>}</g>})}
  <text x="170" y="290" textAnchor="middle" fill="#b3d5de" fontSize="11">Fictional plate · No clinical interpretation</text>
 </svg><label className="pitch-boundary"><span>{demoDiscs[disc].code} example diameter <b>{mm.toFixed(1)} mm</b></span><input type="range" aria-label="Pitch example zone diameter" min="6" max="40" step="0.1" value={mm} onChange={e=>setMm(Number(e.target.value))}/></label></div>;
}
function PitchWorkflow(){const [step,setStep]=useState(0);const icons=[Camera,Ruler,Users,Database];const Icon=icons[step];return <div className="pitch-workflow-scene"><div className="pitch-flow-choice">{workflow.map(([name],i)=>{const I=icons[i];return <button key={name} onClick={()=>setStep(i)} aria-pressed={step===i}><I/><span>{name}</span></button>})}</div><div className="pitch-record"><Icon size={46}/><span className="visual-kicker">{step+1} / 4</span><h3>{workflow[step][0]}</h3><div className="record-lines">{['Original image','Scale + measurement','Human decision','Audit record'].map((name,i)=><div key={name} className={i<=step?'record-revealed':''}><span>{i<=step?<Check size={15}/>:<LockKeyhole size={15}/>}</span>{name}</div>)}</div><p>{workflow[step][1]}</p></div></div>}
function PitchProducts(){const [choice,setChoice]=useState(0);const item=configurations[choice];const Icon=item.icon;return <div className="pitch-product-scene"><div className="visual-segmented">{configurations.map((p,i)=><button key={p.name} aria-pressed={choice===i} onClick={()=>setChoice(i)}>{p.name}</button>)}</div><div className="pitch-product-core"><Icon size={54}/><h3>{item.name}</h3><small>{item.state}</small></div><div className="pitch-capabilities">{item.features.map((f,i)=><div key={f}><span>0{i+1}</span><b>{f}</b></div>)}</div><p>{item.note}</p></div>}
function PitchNetwork(){const [step,setStep]=useState(0);const names=['Local record','Access check','Approved aggregate','Research review'];return <div className="pitch-network-scene"><div className="pitch-network-nodes">{names.map((n,i)=><button key={n} onClick={()=>setStep(i)} aria-pressed={step===i}><span>{i===0?<Microscope/>:i===1?<LockKeyhole/>:i===2?<Cloud/>:<Users/>}</span><b>{n}</b>{i<3&&<ChevronRight className="network-connector"/>}</button>)}</div><div className="privacy-record"><span className="visual-kicker">{names[step]}</span>{['Sample identity','Measured result','Review history'].map((n,i)=><div key={n}><span>{n}</span><b>{step<2?(i===0?'Local only':'Controlled record'):(i===0?'Not shared':i===1?'Approved summary':'Quality context')}</b>{step>=2&&i===0?<LockKeyhole size={17}/>:<Check size={17}/>}</div>)}</div><p>{['Records begin inside a laboratory.','Permissions and data quality need checking.','Only agreed, appropriately de-identified aggregates would cross this boundary.','Any interpretation needs context and qualified review.'][step]}</p></div>}
export function EvidenceGates(){const [gate,setGate]=useState(0);return <div className="evidence-gates"><div className="evidence-ladder">{gates.map(([name,,state],i)=><button key={name} onClick={()=>setGate(i)} aria-pressed={gate===i}><span className="evidence-number">0{i+1}</span><span><b>{name}</b><small>{state}</small></span><ChevronRight/></button>)}</div><div className="evidence-note" role="status"><ShieldCheck/><p>{gates[gate][1]}</p></div></div>}
function PitchAudience(){const [choice,setChoice]=useState(0);const choices=[['Laboratory','Map the real workflow and the evidence a tool would need.',Microscope],['Research','Help define a study, comparison method or dataset question.',GraduationCap],['Public health','Explore governed reporting and practical implementation needs.',Users]] as const;return <div className="pitch-audience-scene">{choices.map(([label,copy,Icon],i)=><button key={label} onClick={()=>setChoice(i)} aria-pressed={choice===i}><Icon/><b>{label}</b><span>{i===choice?copy:'Explore this perspective'}</span><ChevronRight/></button>)}</div>}

export default function VisualPitch({onExit,onNavigate}:{onExit:()=>void;onNavigate:(id:string)=>void}){
 const [index,setIndex]=useState(0),[duration,setDuration]=useState(4),[seconds,setSeconds]=useState(0),[running,setRunning]=useState(false);
 useEffect(()=>{const n=Number(new URLSearchParams(location.search).get('slide'));if(n>=1&&n<=6)setIndex(n-1)},[]);
 const choose=(n:number)=>{setIndex(n);const u=new URL(location.href);u.searchParams.set('slide',String(n+1));history.replaceState({},'',u)};
 useEffect(()=>{const key=(e:KeyboardEvent)=>{if((e.target as HTMLElement).closest('input,select,textarea,[role=button]'))return;if(e.key==='ArrowRight'){e.preventDefault();choose(Math.min(5,index+1))}if(e.key==='ArrowLeft'){e.preventDefault();choose(Math.max(0,index-1))}};window.addEventListener('keydown',key);return()=>window.removeEventListener('keydown',key)},[index]);
 useEffect(()=>{if(!running)return;const start=Date.now()-seconds*1000;const timer=setInterval(()=>setSeconds(Math.floor((Date.now()-start)/1000)),1000);return()=>clearInterval(timer)},[running]);
 useEffect(()=>{if(seconds>=duration*60)setRunning(false)},[seconds,duration]);
 const left=Math.max(0,duration*60-seconds),item=slides[index];
 return <div className="visual-pitch"><header><span>AMReye.AI <b>QUICK PITCH</b></span><button onClick={onExit} aria-label="Exit quick pitch"><X size={19}/>Close</button></header><div className="visual-pitch-layout"><div className="visual-pitch-scene" key={index}><span className="visual-scene-instruction">{item.prompt}</span>{index===0?<PitchPlate/>:index===1?<PitchWorkflow/>:index===2?<PitchProducts/>:index===3?<PitchNetwork/>:index===4?<EvidenceGates/>:<PitchAudience/>}</div><div className="visual-pitch-copy"><span className="visual-kicker">0{index+1} / 06 · {item.label}</span><h2>{item.title}</h2><p>{item.copy}</p><small>{item.status}</small><button className="solid-link" onClick={()=>onNavigate(item.target)}>{item.link}<ArrowRight size={17}/></button></div></div><footer><button aria-label="Previous pitch slide" disabled={index===0} onClick={()=>choose(index-1)}><ArrowLeft/></button><nav aria-label="Pitch slides">{slides.map((s,i)=><button key={s.label} onClick={()=>choose(i)} aria-label={`Slide ${i+1}: ${s.label}`} aria-current={index===i?'step':undefined}>{i+1}</button>)}</nav><button onClick={()=>index===5?onExit():choose(index+1)}>{index===5?'Finish':'Next'}<ArrowRight size={18}/></button></footer><div className="visual-pitch-timer"><label>Guide length<select value={duration} onChange={e=>{setDuration(Number(e.target.value));setSeconds(0);setRunning(false)}}>{[3,4,5].map(n=><option key={n} value={n}>{n} minutes</option>)}</select></label><span role="timer" aria-label="Time remaining">{Math.floor(left/60)}:{String(left%60).padStart(2,'0')}</span><button onClick={()=>setRunning(!running)}><Play size={14}/>{running?'Pause timer':'Start timer'}</button><button onClick={()=>{choose(0);setSeconds(0);setRunning(false)}}>Restart</button></div><p className="visual-pitch-safety">Synthetic examples · Proposed capabilities are not validated clinical features.</p></div>;
}
