"use client";
import {useState} from 'react';
import {ArrowUpRight, Camera, Ruler, UserCheck, Network} from 'lucide-react';
const steps=[
 {title:'Capture',icon:Camera,meaning:'Take a clear, calibrated photograph of the test plate.',why:'Known scale and controlled lighting help make measurements comparable.',href:'/library?topic=reader-v1'},
 {title:'Measure',icon:Ruler,meaning:'Measure the clear zones around antibiotic discs.',why:'A measurement is useful only when image quality and uncertainty are recorded.',href:'/#demo'},
 {title:'Review',icon:UserCheck,meaning:'Let a qualified person review the result and any warning.',why:'Corrections invalidate previous approval. Unreadable results remain unavailable.',href:'/library?topic=research-readability'},
 {title:'Connect',icon:Network,meaning:'Keep the image, measurement and review together in a laboratory record.',why:'Connections to laboratory systems are a proposed pathway that needs testing.',href:'/library?topic=interoperability'}
];
export default function Workflow(){const [index,setIndex]=useState(0);const step=steps[index];const Icon=step.icon;return <section className="section editorial-page amr-workflow"><span className="eyebrow">From sample to insight</span><h1>How the workflow fits together.</h1><p>The website demonstrates a synthetic plate review. Instrument integration and clinical validation remain development work.</p><div className="workflow-tabs" role="tablist" aria-label="Plate workflow">{steps.map((s,i)=><button key={s.title} role="tab" id={'workflow-tab-'+i} aria-selected={i===index} aria-controls="workflow-detail" tabIndex={i===index?0:-1} onClick={()=>setIndex(i)} onKeyDown={e=>{let n=i;if(e.key==='ArrowRight')n=(i+1)%4;else if(e.key==='ArrowLeft')n=(i+3)%4;else if(e.key==='Home')n=0;else if(e.key==='End')n=3;else return;e.preventDefault();setIndex(n);document.getElementById('workflow-tab-'+n)?.focus()}}>{s.title}</button>)}</div><div className="workflow-visual-track" aria-hidden="true">{steps.map((s,i)=>{const StepIcon=s.icon;return <div key={s.title} data-selected={i===index}><StepIcon/><span>{s.title}</span></div>})}</div><div id="workflow-detail" role="tabpanel" aria-labelledby={'workflow-tab-'+index} className="offline-card"><Icon aria-hidden="true"/><h2>{step.meaning}</h2><p>{step.why}</p><a className="solid-link" href={step.href}>Explore this step<ArrowUpRight size={18}/></a></div></section>}
